import { beforeEach, describe, expect, it } from "vitest";
import { env, SELF } from "cloudflare:test";
import { DEFAULT_WORKSPACE_ID, hashToken, SESSION_COOKIE } from "../worker/auth";
import { scheduleChecks } from "../worker/app";

const origin = "https://app.test";
const json = (response: Response) => response.json() as Promise<{ data?: any; error?: { code: string } }>;
const stateFrom = (response: Response) => new URL(response.headers.get("location")!).searchParams.get("state")!;
async function begin(returnTo = "/") { return SELF.fetch(`${origin}/api/auth/github?returnTo=${encodeURIComponent(returnTo)}`, { redirect: "manual" }); }
async function login(code = "owner", returnTo = "/dashboard") { const started = await begin(returnTo), state = stateFrom(started); const callback = await SELF.fetch(`${origin}/api/auth/github/callback?code=${code}&state=${encodeURIComponent(state)}`, { redirect: "manual" }); const setCookie = callback.headers.get("set-cookie")!; return { callback, cookie: setCookie.split(";")[0]!, token: setCookie.split(";")[0]!.split("=")[1]! }; }
function authed(path: string, cookie: string, init: RequestInit = {}, workspaceId = DEFAULT_WORKSPACE_ID) { const headers = new Headers(init.headers); headers.set("cookie", cookie); headers.set("x-workspace-id", workspaceId); if (["POST", "PATCH", "PUT", "DELETE"].includes(init.method ?? "GET")) headers.set("origin", origin); return SELF.fetch(`${origin}${path}`, { ...init, headers }); }

beforeEach(async () => {
	await env.DB.prepare("DELETE FROM alert_deliveries").run(); await env.DB.prepare("DELETE FROM incident_events").run(); await env.DB.prepare("DELETE FROM incidents").run(); await env.DB.prepare("DELETE FROM check_results").run(); await env.DB.prepare("DELETE FROM monitoring_jobs").run(); await env.DB.prepare("DELETE FROM endpoints").run();
	await env.DB.prepare("DELETE FROM sessions").run(); await env.DB.prepare("DELETE FROM oauth_states").run(); await env.DB.prepare("DELETE FROM workspace_memberships").run(); await env.DB.prepare("DELETE FROM users").run(); await env.DB.prepare("DELETE FROM workspaces WHERE id<>?").bind(DEFAULT_WORKSPACE_ID).run(); await env.DB.prepare("UPDATE workspaces SET created_by=NULL WHERE id=?").bind(DEFAULT_WORKSPACE_ID).run();
});

describe("GitHub OAuth and sessions", () => {
	it("serves logged-out invitation navigation from the SPA while keeping invitation APIs authenticated", async () => { const page = await SELF.fetch(`${origin}/invite/test-token`, { headers: { accept: "text/html" } }); expect(page.status).toBe(200); expect(page.headers.get("content-type")).toContain("text/html"); expect(await page.text()).toContain('<div id="root"></div>'); const frontend = await SELF.fetch(`${origin}/settings`, { headers: { accept: "text/html" } }); expect(frontend.status).toBe(200); expect(frontend.headers.get("content-type")).toContain("text/html"); const api = await SELF.fetch(`${origin}/api/invitations/test-token`); expect(api.status).toBe(401); expect(await json(api)).toMatchObject({ error: { code: "UNAUTHORIZED" } }); });
	it("preserves a safe invitation return path through GitHub login", async () => { const path = "/invite/test-token", started = await begin(path), state = stateFrom(started); expect(await env.DB.prepare("SELECT return_to FROM oauth_states WHERE state_hash=?").bind(await hashToken(state)).first()).toMatchObject({ return_to: path }); const callback = await SELF.fetch(`${origin}/api/auth/github/callback?code=owner&state=${encodeURIComponent(state)}`, { redirect: "manual" }); expect(callback.status).toBe(302); expect(callback.headers.get("location")).toBe(path); });
	it("rejects missing and malformed sessions with hardened responses", async () => { const response = await SELF.fetch(`${origin}/api/endpoints`); expect(response.status).toBe(401); expect(await json(response)).toMatchObject({ error: { code: "UNAUTHORIZED" } }); expect(response.headers.get("content-security-policy")).toContain("frame-ancestors 'none'"); expect((await SELF.fetch(`${origin}/api/endpoints`, { headers: { cookie: `${SESSION_COOKIE}=short` } })).status).toBe(401); });
	it("keeps unknown authenticated API paths as JSON 404 responses", async () => { const { cookie } = await login(); const response = await authed("/api/does-not-exist", cookie); expect(response.status).toBe(404); expect(response.headers.get("content-type")).toContain("application/json"); expect(await json(response)).toMatchObject({ error: { code: "NOT_FOUND" } }); });
	it("validates return paths and stores only hashed OAuth state", async () => { for (const unsafe of ["https://evil.test", "//evil.test/path", "/\\evil", "javascript:alert(1)"]) { const response = await begin(unsafe); const state = stateFrom(response); const row = await env.DB.prepare("SELECT state_hash,return_to FROM oauth_states WHERE state_hash=?").bind(await hashToken(state)).first<{ state_hash: string; return_to: string }>(); expect(row?.return_to).toBe("/"); expect(row?.state_hash).not.toBe(state); await env.DB.prepare("DELETE FROM oauth_states").run(); } });
	it("logs in through mocked GitHub, bootstraps only the configured owner, and hashes the session", async () => { const { callback, cookie, token } = await login(); expect(callback.status).toBe(302); expect(callback.headers.get("location")).toBe("/dashboard"); expect(callback.headers.get("set-cookie")).toContain("HttpOnly"); expect(callback.headers.get("set-cookie")).toContain("Secure"); expect(callback.headers.get("set-cookie")).toContain("SameSite=Lax"); const stored = await env.DB.prepare("SELECT token_hash FROM sessions").first<{ token_hash: string }>(); expect(stored?.token_hash).toBe(await hashToken(token)); expect(stored?.token_hash).not.toBe(token); expect(await env.DB.prepare("SELECT role FROM workspace_memberships WHERE workspace_id=?").bind(DEFAULT_WORKSPACE_ID).first()).toMatchObject({ role: "OWNER" }); const session = await authed("/api/auth/session", cookie); expect(await json(session)).toMatchObject({ data: { user: { githubLogin: "test-owner" }, workspaces: [{ id: DEFAULT_WORKSPACE_ID, role: "OWNER" }] } }); });
	it("rejects missing, invalid, expired, and reused OAuth state", async () => { expect((await SELF.fetch(`${origin}/api/auth/github/callback?code=x`)).status).toBe(400); expect((await SELF.fetch(`${origin}/api/auth/github/callback?code=x&state=invalid`)).status).toBe(400); const started = await begin(), state = stateFrom(started); await env.DB.prepare("UPDATE oauth_states SET expires_at='2000-01-01T00:00:00.000Z'").run(); expect((await SELF.fetch(`${origin}/api/auth/github/callback?code=x&state=${state}`)).status).toBe(400); const fresh = stateFrom(await begin()); expect((await SELF.fetch(`${origin}/api/auth/github/callback?code=x&state=${fresh}`, { redirect: "manual" })).status).toBe(302); expect((await SELF.fetch(`${origin}/api/auth/github/callback?code=x&state=${fresh}`, { redirect: "manual" })).status).toBe(400); });
	it("returns OAuth denial to the safe application path", async () => { const state = stateFrom(await begin("/settings?tab=profile")); const denied = await SELF.fetch(`${origin}/api/auth/github/callback?error=access_denied&state=${state}`, { redirect: "manual" }); expect(denied.status).toBe(302); expect(denied.headers.get("location")).toBe("/settings?tab=profile&authError=oauth_denied"); expect(await env.DB.prepare("SELECT state_hash FROM oauth_states WHERE state_hash=?").bind(await hashToken(state)).first()).toBeNull(); });
	it("rotates an existing session after successful authentication", async () => { const first = await login(); const started = await begin(), state = stateFrom(started); const rotated = await SELF.fetch(`${origin}/api/auth/github/callback?code=owner&state=${state}`, { headers: { cookie: first.cookie }, redirect: "manual" }); const nextToken = rotated.headers.get("set-cookie")!.split(";")[0]!.split("=")[1]!; expect(nextToken).not.toBe(first.token); expect(await env.DB.prepare("SELECT token_hash FROM sessions WHERE token_hash=?").bind(await hashToken(first.token)).first()).toBeNull(); expect(await env.DB.prepare("SELECT token_hash FROM sessions WHERE token_hash=?").bind(await hashToken(nextToken)).first()).not.toBeNull(); });
	it("rejects expired sessions and revokes logout", async () => { const { cookie, token } = await login(); await env.DB.prepare("UPDATE sessions SET expires_at='2000-01-01T00:00:00.000Z' WHERE token_hash=?").bind(await hashToken(token)).run(); expect((await authed("/api/auth/session", cookie)).status).toBe(401); const fresh = await login(); const logout = await authed("/api/auth/logout", fresh.cookie, { method: "POST" }); expect(logout.status).toBe(204); expect(logout.headers.get("set-cookie")).toContain("Max-Age=0"); expect(await env.DB.prepare("SELECT token_hash FROM sessions WHERE token_hash=?").bind(await hashToken(fresh.token)).first()).toBeNull(); });
	it("requires a matching Origin for cookie-authenticated mutations", async () => { const { cookie } = await login(); const body = JSON.stringify({ name: "Blocked" }); const missing = await SELF.fetch(`${origin}/api/workspaces`, { method: "POST", headers: { cookie, "content-type": "application/json" }, body }); expect(missing.status).toBe(403); const foreign = await SELF.fetch(`${origin}/api/workspaces`, { method: "POST", headers: { cookie, origin: "https://evil.test", "content-type": "application/json" }, body }); expect(foreign.status).toBe(403); });
});

describe("workspace authorization", () => {
	it("does not let a normal user claim existing data and permits isolated workspace creation", async () => { await env.DB.prepare("INSERT INTO endpoints(id,workspace_id,name,url,method,expected_status,timeout_ms,latency_threshold_ms,check_interval_minutes,enabled) VALUES('legacy',?,'Legacy','https://legacy.example.test','GET',200,1000,500,5,1)").bind(DEFAULT_WORKSPACE_ID).run(); const { cookie } = await login("normal"); const session = await json(await authed("/api/auth/session", cookie)); expect(session.data.workspaces).toEqual([]); expect(await env.DB.prepare("SELECT user_id FROM workspace_memberships WHERE workspace_id=?").bind(DEFAULT_WORKSPACE_ID).first()).toBeNull(); const createdResponse = await authed("/api/workspaces", cookie, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Normal Team" }) }); expect(createdResponse.status).toBe(201); const created = (await json(createdResponse)).data; expect((await json(await authed("/api/endpoints", cookie, {}, created.id))).data).toEqual([]); expect((await authed("/api/endpoints/legacy", cookie, {}, created.id)).status).toBe(404); });
	it("allows only owners to administer memberships for users who have signed in", async () => { const owner = await login(); const workspace = (await json(await authed("/api/workspaces", owner.cookie, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Managed" }) }))).data; const normal = await login("normal"); const add = await authed(`/api/workspaces/${workspace.id}/members`, owner.cookie, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ githubLogin: "normal-user", role: "MEMBER" }) }, workspace.id); expect(add.status).toBe(201); expect((await authed(`/api/workspaces/${workspace.id}/members`, normal.cookie, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ githubLogin: "test-owner", role: "MEMBER" }) }, workspace.id)).status).toBe(403); });
	it("enforces owner/member permissions and cross-workspace endpoint, job, result, incident, event, and alert isolation", async () => { const owner = await login(); const other = (await json(await authed("/api/workspaces", owner.cookie, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Other" }) }))).data; const now = new Date().toISOString(); await env.DB.prepare("INSERT INTO users(id,github_id,github_login,created_at,updated_at) VALUES('member',3003,'member',?,?)").bind(now, now).run(); await env.DB.prepare("INSERT INTO workspace_memberships(workspace_id,user_id,role,created_at,updated_at) VALUES(?, 'member','MEMBER',?,?)").bind(other.id, now, now).run(); const memberToken = "member-session-token-with-at-least-thirty-two-bytes"; await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at,created_at,last_seen_at) VALUES(?,'member',?,?,?)").bind(await hashToken(memberToken), new Date(Date.now()+3600000).toISOString(), now, now).run(); const memberCookie = `${SESSION_COOKIE}=${memberToken}`; expect((await authed(`/api/workspaces/${other.id}/members`, memberCookie, {}, other.id)).status).toBe(403); expect((await authed(`/api/workspaces/${other.id}/members`, owner.cookie, {}, other.id)).status).toBe(200); expect((await authed("/api/endpoints", memberCookie, {}, DEFAULT_WORKSPACE_ID)).status).toBe(403);
		await env.DB.prepare("INSERT INTO endpoints(id,workspace_id,name,url,method,expected_status,timeout_ms,latency_threshold_ms,check_interval_minutes,enabled,created_at,updated_at) VALUES('private',?,'Private','https://private.example.test','GET',200,1000,500,5,1,?,?)").bind(DEFAULT_WORKSPACE_ID, now, now).run(); await env.DB.prepare("INSERT INTO monitoring_jobs(id,workspace_id,endpoint_id,deduplication_key,source,status,scheduled_for,created_at,updated_at) VALUES('private-job',?,'private','private-job-key','MANUAL','COMPLETED',?,?,?)").bind(DEFAULT_WORKSPACE_ID, now, now, now).run(); await env.DB.prepare("INSERT INTO check_results(id,endpoint_id,job_id,checked_at,status_code,latency_ms,outcome) VALUES('private-result','private','private-job',?,500,10,'CRITICAL')").bind(now).run(); await env.DB.prepare("INSERT INTO incidents(id,workspace_id,endpoint_id,status,severity,title,summary,consecutive_failure_count,started_at,created_at,updated_at) VALUES('private-incident',?,'private','OPEN','CRITICAL','Private','Private',2,?,?,?)").bind(DEFAULT_WORKSPACE_ID, now, now, now).run(); await env.DB.prepare("INSERT INTO incident_events(id,incident_id,event_type,message,created_at) VALUES('private-event','private-incident','OPENED','Private',?)").bind(now).run(); await env.DB.prepare("INSERT INTO alert_deliveries(id,incident_id,incident_event_id,channel,deduplication_key,status,created_at,updated_at) VALUES('private-alert','private-incident','private-event','WEBHOOK','private-alert-key','QUEUED',?,?)").bind(now, now).run();
		expect((await authed("/api/endpoints/private", memberCookie, {}, other.id)).status).toBe(404); expect((await authed("/api/jobs/private-job", memberCookie, {}, other.id)).status).toBe(404); expect((await authed("/api/endpoints/private/results", memberCookie, {}, other.id)).status).toBe(404); for (const suffix of ["", "/events", "/alerts"]) expect((await authed(`/api/incidents/private-incident${suffix}`, memberCookie, {}, other.id)).status).toBe(404); });
	it("keeps Cron scheduling independent of browser sessions", async () => { const now = "2026-09-19T10:00:00.000Z"; await env.DB.prepare("INSERT INTO endpoints(id,workspace_id,name,url,method,expected_status,timeout_ms,latency_threshold_ms,check_interval_minutes,enabled,created_at,updated_at) VALUES('cron-authless',?,'Cron','https://cron.example.test','GET',200,1000,500,5,1,?,?)").bind(DEFAULT_WORKSPACE_ID, now, now).run(); expect((await scheduleChecks(env, new Date("2026-09-19T10:10:00.000Z"))).due).toBe(1); });
});
