import { beforeEach, describe, expect, it, vi } from "vitest";
import { env, SELF } from "cloudflare:test";
import { DEFAULT_WORKSPACE_ID, hashToken, SESSION_COOKIE } from "../worker/auth";
import { redactedRequestPath } from "../worker/http";
import { apiFetch, installTestSession, TEST_TOKEN, TEST_USER_ID } from "./auth-helper";

const origin = "https://app.test";
const parse = (response: Response) => response.json() as Promise<{ data?: any; error?: { code: string; message: string } }>;
const cookie = (token: string) => `${SESSION_COOKIE}=${token}`;
function authenticated(path: string, token: string, init: RequestInit = {}, workspaceId = DEFAULT_WORKSPACE_ID) { const headers = new Headers(init.headers); headers.set("cookie", cookie(token)); headers.set("x-workspace-id", workspaceId); if (["POST", "PATCH", "DELETE", "PUT"].includes(init.method ?? "GET")) headers.set("origin", origin); return SELF.fetch(`${origin}${path}`, { ...init, headers }); }
async function addUser(id: string, login: string, token: string, workspaceId?: string, role: "OWNER" | "MEMBER" = "MEMBER") { const now = new Date().toISOString(), githubId = Number(id.replace(/\D/g, "")) || Array.from(id).reduce((total, character) => total + character.charCodeAt(0), 10_000); await env.DB.prepare("INSERT INTO users(id,github_id,github_login,display_name,avatar_url,created_at,updated_at) VALUES(?,?,?,?,NULL,?,?)").bind(id, githubId, login, login, now, now).run(); if (workspaceId) await env.DB.prepare("INSERT INTO workspace_memberships(workspace_id,user_id,role,created_at,updated_at) VALUES(?,?,?,?,?)").bind(workspaceId, id, role, now, now).run(); await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at,created_at,last_seen_at) VALUES(?,?,?,?,?)").bind(await hashToken(token), id, new Date(Date.now() + 3_600_000).toISOString(), now, now).run(); }
async function createInvite(login = "target-user", expiryDays = 7, workspaceId = DEFAULT_WORKSPACE_ID) { const response = await apiFetch(`${origin}/api/workspaces/${workspaceId}/invitations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ githubLogin: login, role: "MEMBER", expiryDays }) }, workspaceId); return { response, data: (await parse(response)).data as { id: string; invitationUrl: string; invitedGithubLogin: string }, token: "" } as { response: Response; data: { id: string; invitationUrl: string; invitedGithubLogin: string }; token: string }; }

beforeEach(async () => {
	await env.DB.prepare("DELETE FROM workspace_audit_events").run(); await env.DB.prepare("DELETE FROM workspace_invitations").run(); await env.DB.prepare("DELETE FROM alert_deliveries").run(); await env.DB.prepare("DELETE FROM incident_events").run(); await env.DB.prepare("DELETE FROM incidents").run(); await env.DB.prepare("DELETE FROM check_results").run(); await env.DB.prepare("DELETE FROM monitoring_jobs").run(); await env.DB.prepare("DELETE FROM endpoints").run(); await env.DB.prepare("DELETE FROM sessions").run(); await env.DB.prepare("DELETE FROM oauth_states").run(); await env.DB.prepare("DELETE FROM workspace_memberships").run(); await env.DB.prepare("DELETE FROM users").run(); await env.DB.prepare("DELETE FROM workspaces WHERE id<>?").bind(DEFAULT_WORKSPACE_ID).run(); await env.DB.prepare("UPDATE workspaces SET created_by=NULL WHERE id=?").bind(DEFAULT_WORKSPACE_ID).run(); await installTestSession();
});

describe("workspace invitations", () => {
	it("lets an owner create a seven-day invitation while storing only its hash", async () => { const created = await createInvite("Target-User"); expect(created.response.status).toBe(201); expect(created.data.invitedGithubLogin).toBe("target-user"); const token = decodeURIComponent(new URL(created.data.invitationUrl).pathname.split("/").at(-1)!); const row = await env.DB.prepare("SELECT token_hash,invited_github_login,status,expires_at FROM workspace_invitations WHERE id=?").bind(created.data.id).first<{ token_hash: string; invited_github_login: string; status: string; expires_at: string }>(); expect(row).toMatchObject({ token_hash: await hashToken(token), invited_github_login: "target-user", status: "PENDING" }); expect(row?.token_hash).not.toBe(token); expect(JSON.stringify((await env.DB.prepare("SELECT * FROM workspace_invitations WHERE id=?").bind(created.data.id).first()))).not.toContain(token); expect(Date.parse(row!.expires_at) - Date.now()).toBeGreaterThan(6 * 86_400_000); const audit = await env.DB.prepare("SELECT action,metadata FROM workspace_audit_events WHERE invitation_id=?").bind(created.data.id).first<{ action: string; metadata: string }>(); expect(audit?.action).toBe("INVITATION_CREATED"); expect(audit?.metadata).not.toContain(token); });

	it("allows only owners and isolates invitation administration by workspace", async () => { const now = new Date().toISOString(), otherId = "other-team"; await env.DB.prepare("INSERT INTO workspaces(id,name,slug,created_at,updated_at) VALUES(?,?,?, ?,?)").bind(otherId, "Other", "other-team", now, now).run(); const memberToken = "member-team-session-token-at-least-thirty-two-bytes"; await addUser("github:2002", "member-user", memberToken, DEFAULT_WORKSPACE_ID); const denied = await authenticated(`/api/workspaces/${DEFAULT_WORKSPACE_ID}/invitations`, memberToken, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ githubLogin: "someone", role: "MEMBER" }) }); expect(denied.status).toBe(403); expect((await authenticated(`/api/workspaces/${otherId}/invitations`, TEST_TOKEN)).status).toBe(403); });

	it("requires the matching GitHub account case-insensitively and preserves the invite path through login", async () => { const created = await createInvite("Case-Target"), token = new URL(created.data.invitationUrl).pathname.split("/").at(-1)!; const begin = await SELF.fetch(`${origin}/api/auth/github?returnTo=${encodeURIComponent(`/invite/${token}`)}`, { redirect: "manual" }), state = new URL(begin.headers.get("location")!).searchParams.get("state")!; expect(await env.DB.prepare("SELECT return_to FROM oauth_states WHERE state_hash=?").bind(await hashToken(state)).first()).toMatchObject({ return_to: `/invite/${token}` }); const wrongToken = "wrong-invite-user-session-token-thirty-two-bytes"; await addUser("github:3003", "wrong-user", wrongToken); const mismatch = await parse(await authenticated(`/api/invitations/${token}`, wrongToken)); expect(mismatch.data).toMatchObject({ invitedGithubLogin: "case-target", matchesCurrentUser: false }); expect(mismatch.data).not.toHaveProperty("workspace"); expect(mismatch.data).not.toHaveProperty("invitedBy"); expect(mismatch.data).not.toHaveProperty("role"); const wrong = await authenticated(`/api/invitations/${token}/accept`, wrongToken, { method: "POST" }); expect(wrong.status).toBe(403); const targetToken = "matching-invite-user-session-token-thirty-two-bytes"; await addUser("github:4004", "CASE-TARGET", targetToken); const accepted = await authenticated(`/api/invitations/${token}/accept`, targetToken, { method: "POST" }); expect(accepted.status).toBe(200); expect(await env.DB.prepare("SELECT role FROM workspace_memberships WHERE workspace_id=? AND user_id='github:4004'").bind(DEFAULT_WORKSPACE_ID).first()).toMatchObject({ role: "MEMBER" }); });

	it("rejects expired and revoked invitations", async () => { const expired = await createInvite("expired-user"), expiredToken = new URL(expired.data.invitationUrl).pathname.split("/").at(-1)!; await env.DB.prepare("UPDATE workspace_invitations SET expires_at='2000-01-01T00:00:00.000Z' WHERE id=?").bind(expired.data.id).run(); const recipientToken = "expired-recipient-session-token-thirty-two-bytes"; await addUser("github:5005", "expired-user", recipientToken); expect((await authenticated(`/api/invitations/${expiredToken}/accept`, recipientToken, { method: "POST" })).status).toBe(409); expect(await env.DB.prepare("SELECT status FROM workspace_invitations WHERE id=?").bind(expired.data.id).first()).toMatchObject({ status: "EXPIRED" }); const revoked = await createInvite("revoked-user"), revokedToken = new URL(revoked.data.invitationUrl).pathname.split("/").at(-1)!; expect((await apiFetch(`${origin}/api/workspaces/${DEFAULT_WORKSPACE_ID}/invitations/${revoked.data.id}`, { method: "DELETE" })).status).toBe(204); const revokedRecipient = "revoked-recipient-session-token-thirty-two-bytes"; await addUser("github:6006", "revoked-user", revokedRecipient); expect((await authenticated(`/api/invitations/${revokedToken}/accept`, revokedRecipient, { method: "POST" })).status).toBe(409); });

	it("accepts once under concurrent delivery and returns an idempotent result to the same user", async () => { const created = await createInvite("double-user"), token = new URL(created.data.invitationUrl).pathname.split("/").at(-1)!, recipientToken = "double-recipient-session-token-thirty-two-bytes"; await addUser("github:7007", "double-user", recipientToken); const [first, second] = await Promise.all([authenticated(`/api/invitations/${token}/accept`, recipientToken, { method: "POST" }), authenticated(`/api/invitations/${token}/accept`, recipientToken, { method: "POST" })]); expect([first.status, second.status]).toEqual([200, 200]); const again = await parse(await authenticated(`/api/invitations/${token}/accept`, recipientToken, { method: "POST" })); expect(again.data).toMatchObject({ accepted: true, alreadyAccepted: true }); expect((await env.DB.prepare("SELECT COUNT(*) count FROM workspace_memberships WHERE workspace_id=? AND user_id='github:7007'").bind(DEFAULT_WORKSPACE_ID).first<{ count: number }>())?.count).toBe(1); expect((await env.DB.prepare("SELECT COUNT(*) count FROM workspace_audit_events WHERE invitation_id=? AND action='INVITATION_ACCEPTED'").bind(created.data.id).first<{ count: number }>())?.count).toBe(1); });

	it("handles membership added after invitation creation without duplication", async () => { const created = await createInvite("existing-user"), token = new URL(created.data.invitationUrl).pathname.split("/").at(-1)!, recipientToken = "existing-recipient-session-token-thirty-two"; await addUser("github:8008", "existing-user", recipientToken, DEFAULT_WORKSPACE_ID); expect((await authenticated(`/api/invitations/${token}/accept`, recipientToken, { method: "POST" })).status).toBe(200); expect((await env.DB.prepare("SELECT COUNT(*) count FROM workspace_memberships WHERE workspace_id=? AND user_id='github:8008'").bind(DEFAULT_WORKSPACE_ID).first<{ count: number }>())?.count).toBe(1); });

	it("prevents duplicate active invitations and enforces the active limit", async () => { expect((await createInvite("duplicate-user")).response.status).toBe(201); expect((await createInvite("DUPLICATE-USER")).response.status).toBe(409); await env.DB.prepare("DELETE FROM workspace_audit_events").run(); await env.DB.prepare("DELETE FROM workspace_invitations").run(); const now = new Date(), expires = new Date(now.getTime() + 86_400_000).toISOString(); for (let index = 0; index < 50; index++) await env.DB.prepare("INSERT INTO workspace_invitations(id,workspace_id,invited_github_login,role,token_hash,status,invited_by_user_id,expires_at,created_at,updated_at) VALUES(?,?,?,'MEMBER',?,'PENDING',?,?,?,?)").bind(`limit-${index}`, DEFAULT_WORKSPACE_ID, `user-${index}`, `hash-${index}`, TEST_USER_ID, expires, now.toISOString(), now.toISOString()).run(); expect((await createInvite("over-limit")).response.status).toBe(409); });

	it("enforces CSRF and redacts tokens from request logging", async () => { const created = await createInvite("csrf-user"), token = new URL(created.data.invitationUrl).pathname.split("/").at(-1)!; const recipient = "csrf-recipient-session-token-thirty-two-bytes"; await addUser("github:9009", "csrf-user", recipient); const denied = await SELF.fetch(`${origin}/api/invitations/${token}/accept`, { method: "POST", headers: { cookie: cookie(recipient) } }); expect(denied.status).toBe(403); const warning = vi.spyOn(console, "warn").mockImplementation(() => undefined); const secret = "raw-invitation-token-that-must-be-redacted-123", missing = await authenticated(`/api/invitations/${secret}`, recipient), errorBody = await missing.text(); expect(errorBody).not.toContain(secret); expect(redactedRequestPath(`${origin}/api/invitations/${secret}/accept`)).toBe("/api/invitations/[redacted]/accept"); expect(JSON.stringify(warning.mock.calls)).not.toContain(secret); expect(JSON.stringify(warning.mock.calls)).toContain("[redacted]"); warning.mockRestore(); });
});

describe("member management safety", () => {
	it("removes a member without deleting identity and revokes workspace access immediately", async () => { const memberToken = "removable-member-session-token-thirty-two"; await addUser("github:1010", "removable", memberToken, DEFAULT_WORKSPACE_ID); expect((await apiFetch(`${origin}/api/workspaces/${DEFAULT_WORKSPACE_ID}/members/github%3A1010`, { method: "DELETE" })).status).toBe(204); expect(await env.DB.prepare("SELECT id FROM users WHERE id='github:1010'").first()).not.toBeNull(); expect((await authenticated("/api/endpoints", memberToken)).status).toBe(403); expect(await env.DB.prepare("SELECT action,target_user_id FROM workspace_audit_events WHERE action='MEMBER_REMOVED'").first()).toMatchObject({ action: "MEMBER_REMOVED", target_user_id: "github:1010" }); });

	it("prevents removing or demoting the final owner", async () => { expect((await apiFetch(`${origin}/api/workspaces/${DEFAULT_WORKSPACE_ID}/members/${encodeURIComponent(TEST_USER_ID)}`, { method: "DELETE" })).status).toBe(409); const demote = await apiFetch(`${origin}/api/workspaces/${DEFAULT_WORKSPACE_ID}/members/${encodeURIComponent(TEST_USER_ID)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: "MEMBER" }) }); expect(demote.status).toBe(409); expect(await env.DB.prepare("SELECT role FROM workspace_memberships WHERE workspace_id=? AND user_id=?").bind(DEFAULT_WORKSPACE_ID, TEST_USER_ID).first()).toMatchObject({ role: "OWNER" }); });

	it("allows role changes when another owner remains and records sanitized audit metadata", async () => { const secondToken = "second-owner-session-token-thirty-two-bytes"; await addUser("github:1111", "second-owner", secondToken, DEFAULT_WORKSPACE_ID, "OWNER"); const changed = await apiFetch(`${origin}/api/workspaces/${DEFAULT_WORKSPACE_ID}/members/github%3A1111`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: "MEMBER" }) }); expect(changed.status).toBe(200); const audit = await env.DB.prepare("SELECT action,metadata FROM workspace_audit_events WHERE action='MEMBER_ROLE_CHANGED'").first<{ action: string; metadata: string }>(); expect(audit).toMatchObject({ action: "MEMBER_ROLE_CHANGED" }); expect(JSON.parse(audit!.metadata)).toEqual({ fromRole: "OWNER", toRole: "MEMBER" }); expect(audit?.metadata).not.toContain("token"); });
});
