name = "endpoint-sentinel"
main = "worker/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "endpoint-sentinel"
database_id = "443a1db2-5619-4c6d-8690-8d3d8a86b142"
migrations_dir = "migrations"

[observability]
enabled = true
