import type { CheckResult, EndpointRecord } from "../types/monitoring";
import Modal from "./Modal";
import StatusBadge from "./StatusBadge";
interface Props { endpoint: EndpointRecord; results: CheckResult[]; loading: boolean; error: string | null; onClose: () => void; onEdit: () => void }
export default function EndpointDetailsModal({ endpoint, results, loading, error, onClose, onEdit }: Props) {
	const latest = endpoint.latestResult;
	const average = results.length ? Math.round(results.reduce((sum, result) => sum + result.latencyMs, 0) / results.length) : null;
	return <Modal title={`Endpoint details — ${endpoint.name}`} onClose={onClose}><div className="es-details__heading"><StatusBadge status={latest?.status ?? "NOT_CHECKED"} /><button type="button" className="es-btn" onClick={onEdit}>Edit configuration</button></div><dl className="es-details__grid"><div><dt>URL</dt><dd><code>{endpoint.url}</code></dd></div><div><dt>Method</dt><dd>{endpoint.method}</dd></div><div><dt>Latest HTTP</dt><dd>{latest?.actualStatusCode ?? "—"}</dd></div><div><dt>Latest latency</dt><dd>{latest ? `${latest.latencyMs} ms` : "—"}</dd></div><div><dt>Average latency</dt><dd>{average === null ? "—" : `${average} ms`}</dd></div><div><dt>Expected status</dt><dd>{endpoint.expectedStatus}</dd></div><div><dt>Timeout</dt><dd>{endpoint.timeoutMs} ms</dd></div><div><dt>Latency threshold</dt><dd>{endpoint.latencyThresholdMs} ms</dd></div><div><dt>Check interval</dt><dd>{endpoint.checkIntervalMinutes} min</dd></div><div><dt>Enabled</dt><dd>{endpoint.enabled ? "Yes" : "No"}</dd></div></dl><h3>Recent results</h3>{loading ? <p role="status">Loading result history…</p> : error ? <p className="es-form__error" role="alert">{error}</p> : results.length === 0 ? <p>No checks have completed yet.</p> : <ul className="es-history">{results.map((result) => <li className="es-history__item" key={result.id}><header className="es-history__header"><StatusBadge status={result.status} /><time className="es-history__time" dateTime={result.checkedAt}>{new Date(result.checkedAt).toLocaleString()}</time></header><p>{result.actualStatusCode ?? "No HTTP response"} · {result.latencyMs} ms</p><p className="es-history__reason">{result.reason}</p></li>)}</ul>}</Modal>;
}
