import { useCallback, useEffect, useState } from "react";
import { incidentsApi } from "../services/endpointsApi";
import type { AlertDelivery, IncidentDetail, IncidentEvent, IncidentPage, IncidentSeverity, IncidentStatus, IncidentSummary } from "../types/monitoring";
import Modal from "./Modal";

interface Props { refreshToken: number; onChanged: () => void }
const duration = (incident: IncidentSummary) => { const end = incident.resolvedAt ? Date.parse(incident.resolvedAt) : Date.now(); const minutes = Math.max(0, Math.round((end - Date.parse(incident.startedAt)) / 60_000)); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; };
const message = (error: unknown) => error instanceof Error ? error.message : "Could not load incidents.";

export default function IncidentsSection({ refreshToken, onChanged }: Props) {
	const [status, setStatus] = useState<IncidentStatus | "">(""), [severity, setSeverity] = useState<IncidentSeverity | "">("");
	const [page, setPage] = useState<IncidentPage | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null);
	const [selected, setSelected] = useState<IncidentDetail | null>(null), [events, setEvents] = useState<IncidentEvent[]>([]), [alerts, setAlerts] = useState<AlertDelivery[]>([]), [detailError, setDetailError] = useState<string | null>(null), [busy, setBusy] = useState(false);
	const load = useCallback(async () => { setLoading(true); setError(null); try { setPage(await incidentsApi.list({ status, severity, limit: 50 })); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } }, [severity, status]);
	useEffect(() => { void load(); }, [load, refreshToken]);
	async function open(incident: IncidentSummary) { setDetailError(null); try { const [detail, timeline, deliveries] = await Promise.all([incidentsApi.get(incident.id), incidentsApi.events(incident.id), incidentsApi.alerts(incident.id)]); setSelected(detail); setEvents(timeline); setAlerts(deliveries); } catch (cause) { setError(message(cause)); } }
	async function action(kind: "acknowledge" | "resolve") { if (!selected) return; setBusy(true); setDetailError(null); try { const updated = kind === "acknowledge" ? await incidentsApi.acknowledge(selected.id) : await incidentsApi.resolve(selected.id); setSelected(updated); setEvents(await incidentsApi.events(updated.id)); setAlerts(await incidentsApi.alerts(updated.id)); await load(); onChanged(); } catch (cause) { setDetailError(message(cause)); } finally { setBusy(false); } }
	return <section className="es-incidents" aria-labelledby="incidents-title">
		<header className="es-section-heading"><div><h2 id="incidents-title">Incidents</h2><p>Operational state changes generated from persisted monitoring results.</p></div></header>
		<div className="es-incident-summary" aria-label="Incident summary"><div><span>Open incidents</span><strong>{page?.counts.open ?? 0}</strong></div><div><span>Critical incidents</span><strong>{page?.counts.critical ?? 0}</strong></div><div><span>Resolved incidents</span><strong>{page?.counts.resolved ?? 0}</strong></div></div>
		<div className="es-filters"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as IncidentStatus | "")}><option value="">All statuses</option><option value="OPEN">Open</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="RESOLVED">Resolved</option></select></label><label>Severity<select value={severity} onChange={(event) => setSeverity(event.target.value as IncidentSeverity | "")}><option value="">All severities</option><option value="DEGRADED">Degraded</option><option value="CRITICAL">Critical</option></select></label></div>
		{loading ? <p className="es-loading" role="status">Loading incidents…</p> : error ? <div className="es-error-state" role="alert"><p>{error}</p><button className="es-btn" type="button" onClick={() => void load()}>Retry</button></div> : !page?.items.length ? <div className="es-empty"><p>No incidents match the current filters.</p></div> : <div className="es-incident-list">{page.items.map((incident) => <article className="es-incident-row" key={incident.id}><div><div className="es-incident-row__labels"><span className={`es-incident-severity es-incident-severity--${incident.severity.toLowerCase()}`}>{incident.severity}</span><span>{incident.status}</span></div><h3>{incident.endpointName}</h3><p>{incident.summary}</p></div><dl><div><dt>Started</dt><dd>{new Date(incident.startedAt).toLocaleString()}</dd></div><div><dt>Duration</dt><dd>{duration(incident)}</dd></div></dl><button className="es-btn" type="button" onClick={() => void open(incident)}>View incident</button></article>)}</div>}
		{selected ? <Modal title={`Incident — ${selected.endpointName}`} onClose={() => setSelected(null)}><div className="es-incident-detail"><div className="es-incident-row__labels"><span className={`es-incident-severity es-incident-severity--${selected.severity.toLowerCase()}`}>{selected.severity}</span><span>{selected.status}</span></div><p>{selected.summary}</p><p><strong>Started:</strong> {new Date(selected.startedAt).toLocaleString()} · <strong>Duration:</strong> {duration(selected)}</p><div className="es-card__actions">{selected.status === "OPEN" ? <button className="es-btn" type="button" disabled={busy} onClick={() => void action("acknowledge")}>Acknowledge</button> : null}{selected.status !== "RESOLVED" ? <button className="es-btn es-btn--danger" type="button" disabled={busy} onClick={() => void action("resolve")}>Resolve incident</button> : null}</div>{detailError ? <p className="es-form__error" role="alert">{detailError}</p> : null}<h3>Event timeline</h3>{events.length ? <ol className="es-timeline">{events.map((event) => <li key={event.id}><strong>{event.eventType.replaceAll("_", " ")}</strong><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString()}</time><p>{event.message}</p></li>)}</ol> : <p>No events recorded.</p>}<h3>Alert deliveries</h3>{alerts.length ? <ul className="es-alert-list">{alerts.map((alert) => <li key={alert.id}><strong>{alert.status}</strong><span>{alert.channel} · {alert.attemptCount} attempt{alert.attemptCount === 1 ? "" : "s"}</span>{alert.lastError ? <small>{alert.lastError}</small> : null}</li>)}</ul> : <p>No alert was required for this incident.</p>}</div></Modal> : null}
	</section>;
}
