import { useEffect, useRef, useState } from 'react';
import { teamApi, type AuthSession, type InvitationDetail } from '../services/endpointsApi';
import Icon from './Icon';
interface Props { token: string; session: AuthSession; onAccepted: (workspaceId: string) => void; onCancel: () => void }
const message = (error: unknown) => error instanceof Error ? error.message : 'The invitation could not be loaded.';
export default function InvitationPage({ token, session, onAccepted, onCancel }: Props) {
  const [invitation, setInvitation] = useState<InvitationDetail | null>(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const lock = useRef(false);
  useEffect(() => { let current = true; setLoading(true); void (async () => { try { const detail = await teamApi.invitation(token); if (current) setInvitation(detail); } catch (cause) { if (current) setError(message(cause)); } finally { if (current) setLoading(false); } })(); return () => { current = false; }; }, [token]);
  async function accept() { if (lock.current) return; lock.current = true; setBusy(true); setError(null); try { const accepted = await teamApi.acceptInvitation(token); onAccepted(accepted.workspace.id); } catch (cause) { setError(message(cause)); } finally { lock.current = false; setBusy(false); } }
  return <main className="es-auth"><div className="es-auth-card es-invite-card"><span className="es-auth-mark"><Icon name="team" /></span><p className="es-eyebrow">Join a workspace</p><h1>Workspace invitation</h1>{loading ? <p role="status">Loading invitation…</p> : <>{error ? <p className="es-form__error" role="alert">{error}</p> : null}{invitation ? <>{invitation.matchesCurrentUser && invitation.workspace ? <><p><strong>{invitation.invitedBy?.displayName ?? `@${invitation.invitedBy?.githubLogin}`}</strong> invited you to join <strong>{invitation.workspace.name}</strong> as a member.</p><p className="es-form__hint">For @{invitation.invitedGithubLogin}<br />Expires {new Date(invitation.expiresAt).toLocaleString()}</p>{invitation.status === 'PENDING' ? <button className="es-btn es-btn--primary" disabled={busy} onClick={() => void accept()}>{busy ? 'Accepting…' : 'Accept invitation'}</button> : invitation.status === 'ACCEPTED' ? <><p className="es-notice" role="status">This invitation has already been accepted.</p><button className="es-btn es-btn--primary" onClick={() => onAccepted(invitation.workspace!.id)}>Open workspace</button></> : <p className="es-form__error" role="alert">This invitation is {invitation.status.toLowerCase()} and cannot be used. Ask an owner for a new invitation.</p>}</> : <p className="es-form__error" role="alert">This invitation is for <strong>@{invitation.invitedGithubLogin}</strong>, but you are signed in as <strong>@{session.user.githubLogin}</strong>.</p>}</> : null}</>}<button className="es-btn" disabled={busy} onClick={onCancel}>Cancel</button></div></main>;
}
