import { useEffect, useId, useRef, useState, type FormEvent } from 'react';
import { teamApi, type WorkspaceAccess, type WorkspaceInvitation, type WorkspaceMember } from '../services/endpointsApi';
import Modal from './Modal';
import Avatar from './Avatar';
interface Props { workspace: WorkspaceAccess; currentUserId: string; onClose: () => void; onMembershipChanged: () => void }
const message = (error: unknown) => error instanceof Error ? error.message : 'The team could not be updated.';
export default function TeamModal({ workspace, currentUserId, onClose, onMembershipChanged }: Props) {
  const [members, setMembers] = useState<WorkspaceMember[]>([]), [invitations, setInvitations] = useState<WorkspaceInvitation[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null);
  const [login, setLogin] = useState(''), [expiryDays, setExpiryDays] = useState(7), [busy, setBusy] = useState<string | null>(null), [newLink, setNewLink] = useState<string | null>(null);
  const [removing, setRemoving] = useState<WorkspaceMember | null>(null), [validation, setValidation] = useState<string | null>(null), [copied, setCopied] = useState(false);
  const lock = useRef(false), inputRef = useRef<HTMLInputElement>(null), inputId = useId();
  async function load() { setLoading(true); try { const [people, invites] = await Promise.all([teamApi.members(workspace.id), teamApi.invitations(workspace.id)]); setMembers(people); setInvitations(invites); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [workspace.id]);
  async function mutation(id: string, work: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(id); setError(null); setNotice(null); try { await work(); } catch (cause) { setError(message(cause)); } finally { lock.current = false; setBusy(null); } }
  async function invite(event: FormEvent) {
    event.preventDefault();
    if (!/^(?!-)(?!.*--)[a-z0-9-]{1,39}(?<!-)$/i.test(login.trim())) { setValidation('Enter a valid GitHub username (1–39 letters, numbers, or single hyphens).'); inputRef.current?.focus(); return; }
    setValidation(null);
    await mutation('invite', async () => { setNewLink(null); setCopied(false); const created = await teamApi.createInvitation(workspace.id, login, expiryDays); setNewLink(created.invitationUrl); setLogin(''); setNotice(`Invitation created for @${created.invitedGithubLogin}.`); await load(); });
  }
  async function copyLink() { if (!newLink) return; try { await navigator.clipboard.writeText(newLink); setCopied(true); setNotice('Invitation link copied. Share it privately with the invited teammate.'); } catch { setError('The link could not be copied. Copy it from the field instead.'); } }
  async function revoke(invitation: WorkspaceInvitation) { await mutation(invitation.id, async () => { await teamApi.revokeInvitation(workspace.id, invitation.id); setNotice(`Invitation for @${invitation.invitedGithubLogin} revoked.`); await load(); }); }
  async function changeRole(member: WorkspaceMember, role: 'OWNER' | 'MEMBER') { await mutation(member.id, async () => { await teamApi.updateMember(workspace.id, member.id, role); setNotice(`@${member.githubLogin} is now ${role.toLowerCase()}.`); await load(); onMembershipChanged(); }); }
  async function remove() { if (!removing) return; await mutation(removing.id, async () => { await teamApi.removeMember(workspace.id, removing.id); setNotice(`@${removing.githubLogin} was removed.`); setRemoving(null); await load(); onMembershipChanged(); }); }
  const onlyOwner = members.filter(member => member.role === 'OWNER').length === 1;
  return <><Modal title={`Team — ${workspace.name}`} onClose={onClose} closeDisabled={busy !== null} size="wide"><div className="es-team"><section><p className="es-eyebrow">Workspace access / Owner controls</p><h3>Invite a teammate</h3><p className="es-form__hint">A private, single-use invitation for one GitHub account. New teammates join as members.</p><form onSubmit={e => void invite(e)} noValidate><div className="es-team-form"><label className="es-form__field" htmlFor={inputId}><span className="es-form__label">GitHub username <span className="es-form__required" aria-hidden="true">*</span></span><input ref={inputRef} id={inputId} className="es-form__input" required value={login} disabled={busy !== null} autoComplete="off" placeholder="octocat" aria-invalid={!!validation} aria-describedby={validation ? `${inputId}-error` : undefined} onChange={e => setLogin(e.target.value)} /></label><label className="es-form__field"><span className="es-form__label">Expires in</span><select className="es-form__select" disabled={busy !== null} value={expiryDays} onChange={e => setExpiryDays(Number(e.target.value))}>{[1, 3, 7, 14].map(days => <option key={days} value={days}>{days} day{days === 1 ? '' : 's'}</option>)}</select></label><button className="es-btn es-btn--primary" disabled={busy !== null}>{busy === 'invite' ? 'Creating…' : 'Create invitation'}</button></div>{validation ? <p id={`${inputId}-error`} className="es-field-error" role="alert">{validation}</p> : null}</form>{newLink ? <><div className="es-copy-row"><input className="es-form__input" value={newLink} readOnly aria-label="Invitation link" /><button className="es-btn" onClick={() => void copyLink()}>{copied ? 'Copied' : 'Copy link'}</button></div><p className="es-form__hint">This private link is shown only now. Share it with the named recipient.</p></> : null}</section>
    {notice ? <p className="es-notice" role="status">{notice}</p> : null}{error ? <div className="es-form__error" role="alert">{error}{!busy ? <button className="es-btn" onClick={() => { setError(null); void load(); }}>Retry team</button> : null}</div> : null}
    <section><h3>Members <span className="es-section-count">{members.length}</span></h3><p className="es-form__hint">At least one owner must remain. You cannot remove your own membership here.</p>{loading ? <p role="status">Loading team…</p> : !members.length ? <p>No members found.</p> : <ul className="es-team-list">{members.map(member => <li key={member.id}><div className="es-team-person"><Avatar name={member.githubLogin} url={member.avatarUrl} /><div><strong>{member.displayName ?? member.githubLogin}{member.id === currentUserId ? ' (you)' : ''}</strong><small>@{member.githubLogin}</small></div></div><div className="es-team-actions"><select aria-label={`Role for ${member.githubLogin}`} title={onlyOwner && member.role === 'OWNER' ? 'At least one owner must remain' : 'Workspace role'} value={member.role} disabled={busy !== null || onlyOwner && member.role === 'OWNER'} onChange={e => void changeRole(member, e.target.value as 'OWNER' | 'MEMBER')}><option value="OWNER">Owner</option><option value="MEMBER">Member</option></select><button className="es-btn es-btn--quiet es-btn--danger-text" disabled={busy !== null || member.id === currentUserId || onlyOwner && member.role === 'OWNER'} onClick={() => setRemoving(member)}>Remove</button></div></li>)}</ul>}</section>
    <section><h3>Invitations</h3>{!loading && !invitations.length ? <p className="es-form__hint">No invitations yet.</p> : <ul className="es-team-list">{invitations.map(invitation => <li key={invitation.id}><div><strong>@{invitation.invitedGithubLogin}</strong><small>Expires {new Date(invitation.expiresAt).toLocaleString()}</small></div><div className="es-team-actions"><span className="es-invitation-status">{invitation.status}</span>{invitation.status === 'PENDING' ? <button className="es-btn" disabled={busy !== null} onClick={() => void revoke(invitation)}>{busy === invitation.id ? 'Revoking…' : 'Revoke'}</button> : null}</div></li>)}</ul>}</section></div></Modal>
    {removing ? <Modal title="Remove team member?" onClose={() => setRemoving(null)} closeDisabled={busy !== null} size="small"><p>Remove <strong>@{removing.githubLogin}</strong> from <strong>{workspace.name}</strong>? They will lose access to this workspace.</p>{error ? <p className="es-form__error" role="alert">{error}</p> : null}<div className="es-form__actions"><button data-autofocus className="es-btn" disabled={busy !== null} onClick={() => setRemoving(null)}>Cancel</button><button className="es-btn es-btn--danger" disabled={busy !== null} onClick={() => void remove()}>{busy ? 'Removing…' : 'Remove member'}</button></div></Modal> : null}</>;
}
