import { useEffect, useState } from "react";
import { teamApi, type WorkspaceAccess, type WorkspaceInvitation, type WorkspaceMember } from "../services/endpointsApi";
import Modal from "./Modal";

interface Props { workspace: WorkspaceAccess; currentUserId: string; onClose: () => void; onMembershipChanged: () => void }
const message = (error: unknown) => error instanceof Error ? error.message : "The team could not be updated.";

export default function TeamModal({ workspace, currentUserId, onClose, onMembershipChanged }: Props) {
	const [members, setMembers] = useState<WorkspaceMember[]>([]), [invitations, setInvitations] = useState<WorkspaceInvitation[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState<string | null>(null);
	const [login, setLogin] = useState(""), [expiryDays, setExpiryDays] = useState(7), [busy, setBusy] = useState<string | null>(null), [newLink, setNewLink] = useState<string | null>(null);
	async function load() { setLoading(true); setError(null); try { const [nextMembers, nextInvitations] = await Promise.all([teamApi.members(workspace.id), teamApi.invitations(workspace.id)]); setMembers(nextMembers); setInvitations(nextInvitations); } catch (cause) { setError(message(cause)); } finally { setLoading(false); } }
	useEffect(() => { void load(); }, [workspace.id]);
	async function invite() { setBusy("invite"); setError(null); setNotice(null); setNewLink(null); try { const created = await teamApi.createInvitation(workspace.id, login, expiryDays); setNewLink(created.invitationUrl); setLogin(""); setNotice(`Invitation created for @${created.invitedGithubLogin}.`); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(null); } }
	async function copyLink() { if (!newLink) return; try { await navigator.clipboard.writeText(newLink); setNotice("Invitation link copied. Share it privately with the invited teammate."); } catch { setError("The link could not be copied. Copy it from the field instead."); } }
	async function revoke(invitation: WorkspaceInvitation) { setBusy(invitation.id); setError(null); try { await teamApi.revokeInvitation(workspace.id, invitation.id); setNotice(`Invitation for @${invitation.invitedGithubLogin} revoked.`); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(null); } }
	async function changeRole(member: WorkspaceMember, role: "OWNER" | "MEMBER") { setBusy(member.id); setError(null); try { await teamApi.updateMember(workspace.id, member.id, role); setNotice(`@${member.githubLogin} is now ${role.toLowerCase()}.`); await load(); onMembershipChanged(); } catch (cause) { setError(message(cause)); } finally { setBusy(null); } }
	async function remove(member: WorkspaceMember) { if (!window.confirm(`Remove @${member.githubLogin} from ${workspace.name}?`)) return; setBusy(member.id); setError(null); try { await teamApi.removeMember(workspace.id, member.id); setNotice(`@${member.githubLogin} was removed.`); await load(); onMembershipChanged(); } catch (cause) { setError(message(cause)); } finally { setBusy(null); } }
	return <Modal title={`Team — ${workspace.name}`} onClose={onClose}><div className="es-team">
		<section><h3>Invite a teammate</h3><p className="es-form__hint">Create a private, single-use invitation for a specific GitHub account.</p><div className="es-team-form"><label className="es-form__field"><span className="es-form__label">GitHub username</span><input className="es-form__input" value={login} autoComplete="off" placeholder="octocat" onChange={(event) => setLogin(event.target.value)} /></label><label className="es-form__field"><span className="es-form__label">Expires in</span><select className="es-form__select" value={expiryDays} onChange={(event) => setExpiryDays(Number(event.target.value))}><option value={1}>1 day</option><option value={3}>3 days</option><option value={7}>7 days</option><option value={14}>14 days</option></select></label><button className="es-btn es-btn--primary" disabled={busy !== null || !login.trim()} onClick={() => void invite()}>{busy === "invite" ? "Creating…" : "Create invitation"}</button></div>{newLink ? <div className="es-copy-row"><input className="es-form__input" value={newLink} readOnly aria-label="Invitation link" /><button className="es-btn" onClick={() => void copyLink()}>Copy link</button></div> : null}</section>
		{notice ? <p className="es-notice" role="status">{notice}</p> : null}{error ? <p className="es-form__error" role="alert">{error}</p> : null}
		<section><h3>Members</h3>{loading ? <p role="status">Loading team…</p> : members.length === 0 ? <p>No members found.</p> : <ul className="es-team-list">{members.map((member) => <li key={member.id}><div className="es-team-person">{member.avatarUrl ? <img src={member.avatarUrl} alt="" referrerPolicy="no-referrer" /> : <span aria-hidden="true">{member.githubLogin[0]?.toUpperCase()}</span>}<div><strong>{member.displayName ?? member.githubLogin}</strong><small>@{member.githubLogin}</small></div></div><div className="es-team-actions"><select aria-label={`Role for ${member.githubLogin}`} value={member.role} disabled={busy !== null} onChange={(event) => void changeRole(member, event.target.value as "OWNER" | "MEMBER")}><option value="OWNER">Owner</option><option value="MEMBER">Member</option></select><button className="es-btn es-btn--danger" disabled={busy !== null || member.id === currentUserId} onClick={() => void remove(member)}>Remove</button></div></li>)}</ul>}</section>
		<section><h3>Invitations</h3>{!loading && invitations.length === 0 ? <p>No invitations yet.</p> : <ul className="es-team-list">{invitations.map((invitation) => <li key={invitation.id}><div><strong>@{invitation.invitedGithubLogin}</strong><small>{invitation.status} · expires {new Date(invitation.expiresAt).toLocaleString()}</small></div>{invitation.status === "PENDING" ? <button className="es-btn" disabled={busy !== null} onClick={() => void revoke(invitation)}>Revoke</button> : null}</li>)}</ul>}</section>
	</div></Modal>;
}
