import type { CheckResult, CheckTarget, EndpointRecord, HealthStatus, HttpMethod, MonitoringJob, MonitoringJobSource, MonitoringJobStatus } from "../src/types/monitoring";
import { ENDPOINT_LIMITS, isHttpMethod, validateUrl } from "../src/services/targetValidation";
import { acknowledgeIncident, evaluateIncident, getIncident, getIncidentAlerts, getIncidentEvents, listIncidents, processAlertMessage, recoverIncidentEvaluations, recoverStaleAlerts, resolveIncident } from "./incidents";
import { authenticate, beginGithub, cleanupAuth, createWorkspace, DEFAULT_WORKSPACE_ID, githubCallback, listMembers, listWorkspaces, logout, sessionResponse, setMember, validateOrigin, workspaceById, workspaceFor, type WorkspaceAccess } from "./auth";
import { ApiError, failure, isRecord, JSON_HEADERS, redactedRequestPath, success, withSecurityHeaders } from "./http";
import { acceptInvitation, createInvitation, expireInvitations, getInvitation, listInvitations, removeMember, revokeInvitation, updateMember } from "./team";

export { DEFAULT_WORKSPACE_ID };
const MAX_REDIRECTS = 5, DEFAULT_SCHEDULE_LIMIT = 100, MAX_SCHEDULE_LIMIT = 500, QUEUE_BATCH_SIZE = 100, STALE_QUEUED_MS = 120_000, MAX_QUEUE_ATTEMPTS = 4;
interface EndpointRow { id: string; workspace_id: string; name: string; url: string; method: HttpMethod; expected_status: number; timeout_ms: number; latency_threshold_ms: number; check_interval_minutes: number; enabled: number; created_at: string; updated_at: string }
interface ResultRow { id: string; endpoint_id: string; job_id: string | null; checked_at: string; status_code: number | null; latency_ms: number; outcome: HealthStatus; error_type: string | null; error_message: string | null }
interface JobRow { id: string; workspace_id: string; endpoint_id: string; deduplication_key: string; source: MonitoringJobSource; status: MonitoringJobStatus; scheduled_for: string; attempt_count: number; last_error: string | null; created_at: string; started_at: string | null; completed_at: string | null; updated_at: string }
export interface MonitoringQueueMessage { version: 1; jobId: string; workspaceId: string; endpointId: string; scheduledFor: string; source: MonitoringJobSource }
export function parseQueueMessage(value: unknown): MonitoringQueueMessage | null {
	if (!isRecord(value) || value.version !== 1 || typeof value.jobId !== "string" || !value.jobId || typeof value.workspaceId !== "string" || !value.workspaceId || typeof value.endpointId !== "string" || !value.endpointId || typeof value.scheduledFor !== "string" || !Number.isFinite(Date.parse(value.scheduledFor)) || (value.source !== "SCHEDULED" && value.source !== "MANUAL")) return null;
	return { version: 1, jobId: value.jobId, workspaceId: value.workspaceId, endpointId: value.endpointId, scheduledFor: new Date(value.scheduledFor).toISOString(), source: value.source };
}
async function readJson(request: Request): Promise<Record<string, unknown>> { let raw: unknown; try { raw = await request.json(); } catch { throw new ApiError(400, "VALIDATION_ERROR", "Request body must be valid JSON."); } if (!isRecord(raw)) throw new ApiError(400, "VALIDATION_ERROR", "Request body must be a JSON object."); return raw; }
function requiredString(value: unknown, field: string): string { if (typeof value !== "string" || !value.trim()) throw new ApiError(400, "VALIDATION_ERROR", `Field '${field}' is required.`); return value.trim(); }
function boundedInt(value: unknown, field: string, min: number, max: number): number { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < min || value > max) throw new ApiError(400, "VALIDATION_ERROR", `Field '${field}' must be an integer from ${min} to ${max}.`); return value; }
export interface EndpointInput { name: string; url: string; method: HttpMethod; expectedStatus: number; timeoutMs: number; latencyThresholdMs: number; checkIntervalMinutes: number; enabled: boolean }
export function validateEndpointInput(raw: Record<string, unknown>, partial = false): Partial<EndpointInput> {
	const out: Partial<EndpointInput> = {}, required = (key: string) => !partial || Object.hasOwn(raw, key);
	if (required("name")) { const name = requiredString(raw.name, "name"); if (name.length < 2 || name.length > ENDPOINT_LIMITS.nameMax || !/[\p{L}\p{N}]/u.test(name)) throw new ApiError(400, "VALIDATION_ERROR", `Name must be 2-${ENDPOINT_LIMITS.nameMax} characters and contain a letter or number.`); out.name = name; }
	if (required("url")) { const url = requiredString(raw.url, "url"), problem = validateUrl(url); if (problem) throw new ApiError(400, "VALIDATION_ERROR", problem); assertPublicUrl(url); out.url = new URL(url).toString(); }
	if (required("method")) { const method = typeof raw.method === "string" ? raw.method.toUpperCase() : raw.method; if (!isHttpMethod(method)) throw new ApiError(400, "VALIDATION_ERROR", "Field 'method' is not a supported HTTP method."); out.method = method; }
	if (required("expectedStatus")) out.expectedStatus = boundedInt(raw.expectedStatus, "expectedStatus", 100, 599);
	if (required("timeoutMs")) out.timeoutMs = boundedInt(raw.timeoutMs, "timeoutMs", ENDPOINT_LIMITS.timeoutMin, ENDPOINT_LIMITS.timeoutMax);
	if (required("latencyThresholdMs")) out.latencyThresholdMs = boundedInt(raw.latencyThresholdMs, "latencyThresholdMs", ENDPOINT_LIMITS.thresholdMin, ENDPOINT_LIMITS.thresholdMax);
	if (required("checkIntervalMinutes")) out.checkIntervalMinutes = boundedInt(raw.checkIntervalMinutes, "checkIntervalMinutes", ENDPOINT_LIMITS.intervalMin, ENDPOINT_LIMITS.intervalMax);
	if (required("enabled")) { if (typeof raw.enabled !== "boolean") throw new ApiError(400, "VALIDATION_ERROR", "Field 'enabled' must be a boolean."); out.enabled = raw.enabled; }
	if (partial && !Object.keys(out).length) throw new ApiError(400, "VALIDATION_ERROR", "Provide at least one editable field."); return out;
}
function isPrivateIpv4(host: string): boolean { const parts = host.split(".").map(Number); if (parts.length !== 4 || parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) return false; const [a = 0, b = 0] = parts; return a === 0 || a === 10 || a === 127 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || a >= 224; }
export function assertPublicUrl(raw: string): void { const host = new URL(raw).hostname.toLowerCase().replace(/^\[|\]$/g, ""); const privateIpv6 = host.includes(":") && (host === "::" || host === "::1" || host.startsWith("fc") || host.startsWith("fd") || /^fe[89ab]/.test(host) || host.startsWith("::ffff:")); if (host === "localhost" || host.endsWith(".localhost") || host.endsWith(".local") || host === "0" || isPrivateIpv4(host) || privateIpv6) throw new ApiError(400, "VALIDATION_ERROR", "Private, local, loopback, link-local, multicast, and unspecified targets are not allowed."); }
const targetFromRow = (row: EndpointRow): CheckTarget => ({ url: row.url, method: row.method, expectedStatus: row.expected_status, timeoutMs: row.timeout_ms, latencyThresholdMs: row.latency_threshold_ms });
function reasonFor(outcome: HealthStatus, code: number | null, latency: number, target: CheckTarget): string { if (code === null) return `No HTTP response was received from ${target.url}.`; if (outcome === "CRITICAL") return `Expected HTTP ${target.expectedStatus} but received HTTP ${code}.`; if (outcome === "DEGRADED") return `Responded HTTP ${code} in ${latency} ms, exceeding the ${target.latencyThresholdMs} ms threshold.`; return `Responded HTTP ${code} in ${latency} ms, within the ${target.latencyThresholdMs} ms threshold.`; }
const resultFromRow = (row: ResultRow, target: CheckTarget): CheckResult => ({ id: row.id, target, status: row.outcome, reason: row.error_message ?? reasonFor(row.outcome, row.status_code, row.latency_ms, target), latencyMs: row.latency_ms, actualStatusCode: row.status_code, checkedAt: row.checked_at });
async function endpointFromRow(db: D1Database, row: EndpointRow): Promise<EndpointRecord> { const [latest, active, incident] = await Promise.all([db.prepare("SELECT * FROM check_results WHERE endpoint_id = ? ORDER BY checked_at DESC, id DESC LIMIT 1").bind(row.id).first<ResultRow>(), db.prepare("SELECT status FROM monitoring_jobs WHERE endpoint_id = ? AND status IN ('QUEUED', 'PROCESSING') ORDER BY created_at DESC LIMIT 1").bind(row.id).first<{ status: "QUEUED" | "PROCESSING" }>(), db.prepare("SELECT id,status,severity FROM incidents WHERE endpoint_id=? AND workspace_id=? AND status IN ('OPEN','ACKNOWLEDGED') LIMIT 1").bind(row.id, row.workspace_id).first<{ id: string; status: "OPEN" | "ACKNOWLEDGED"; severity: "DEGRADED" | "CRITICAL" }>()]); const target = targetFromRow(row); return { id: row.id, workspaceId: row.workspace_id, name: row.name, ...target, checkIntervalMinutes: row.check_interval_minutes, enabled: row.enabled === 1, createdAt: row.created_at, updatedAt: row.updated_at, latestResult: latest ? resultFromRow(latest, target) : null, activeJobStatus: active?.status ?? null, activeIncident: incident ?? null }; }
async function findEndpoint(db: D1Database, id: string, workspaceId: string): Promise<EndpointRow> { const row = await db.prepare("SELECT * FROM endpoints WHERE id = ? AND workspace_id = ?").bind(id, workspaceId).first<EndpointRow>(); if (!row) throw new ApiError(404, "NOT_FOUND", "Endpoint not found."); return row; }
async function listEndpoints(db: D1Database, workspaceId: string): Promise<Response> { const { results } = await db.prepare("SELECT * FROM endpoints WHERE workspace_id = ? ORDER BY created_at ASC").bind(workspaceId).all<EndpointRow>(); return success(await Promise.all(results.map((row) => endpointFromRow(db, row)))); }
async function createEndpoint(request: Request, db: D1Database, workspaceId: string): Promise<Response> { const input = validateEndpointInput(await readJson(request)) as EndpointInput, id = crypto.randomUUID(), now = new Date().toISOString(); await db.prepare("INSERT INTO endpoints (id, workspace_id, name, url, method, expected_status, timeout_ms, latency_threshold_ms, check_interval_minutes, enabled, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)").bind(id, workspaceId, input.name, input.url, input.method, input.expectedStatus, input.timeoutMs, input.latencyThresholdMs, input.checkIntervalMinutes, input.enabled ? 1 : 0, now, now).run(); return success(await endpointFromRow(db, await findEndpoint(db, id, workspaceId)), 201); }
async function updateEndpoint(request: Request, db: D1Database, id: string, workspaceId: string): Promise<Response> { const current = await findEndpoint(db, id, workspaceId), patch = validateEndpointInput(await readJson(request), true); const merged: EndpointInput = { name: patch.name ?? current.name, url: patch.url ?? current.url, method: patch.method ?? current.method, expectedStatus: patch.expectedStatus ?? current.expected_status, timeoutMs: patch.timeoutMs ?? current.timeout_ms, latencyThresholdMs: patch.latencyThresholdMs ?? current.latency_threshold_ms, checkIntervalMinutes: patch.checkIntervalMinutes ?? current.check_interval_minutes, enabled: patch.enabled ?? current.enabled === 1 }; await db.prepare("UPDATE endpoints SET name=?, url=?, method=?, expected_status=?, timeout_ms=?, latency_threshold_ms=?, check_interval_minutes=?, enabled=?, updated_at=? WHERE id=? AND workspace_id=?").bind(merged.name, merged.url, merged.method, merged.expectedStatus, merged.timeoutMs, merged.latencyThresholdMs, merged.checkIntervalMinutes, merged.enabled ? 1 : 0, new Date().toISOString(), id, workspaceId).run(); return success(await endpointFromRow(db, await findEndpoint(db, id, workspaceId))); }

async function fetchWithSafeRedirects(target: CheckTarget, signal: AbortSignal): Promise<Response> { let url = target.url; for (let redirects = 0; redirects <= MAX_REDIRECTS; redirects++) { assertPublicUrl(url); const response = await fetch(url, { method: target.method, signal, redirect: "manual" }); if (![301, 302, 303, 307, 308].includes(response.status)) return response; const location = response.headers.get("location"); void response.body?.cancel(); if (!location) return response; if (redirects === MAX_REDIRECTS) throw new Error("Too many redirects."); url = new URL(location, url).toString(); } throw new Error("Too many redirects."); }
export async function executeCheck(target: CheckTarget): Promise<{ result: CheckResult; errorType: string | null }> { const controller = new AbortController(), timer = setTimeout(() => controller.abort(), target.timeoutMs), started = performance.now(); let response: Response | null = null, errorType: string | null = null, errorMessage: string | null = null; try { response = await fetchWithSafeRedirects(target, controller.signal); void response.body?.cancel().catch(() => undefined); } catch (error) { errorType = error instanceof Error && error.name === "AbortError" ? "TIMEOUT" : "NETWORK_ERROR"; errorMessage = errorType === "TIMEOUT" ? `Request exceeded the ${target.timeoutMs} ms timeout.` : "The target could not be reached."; } finally { clearTimeout(timer); } const latencyMs = Math.round(performance.now() - started), statusCode = response?.status ?? null, outcome: HealthStatus = statusCode === null || statusCode !== target.expectedStatus ? "CRITICAL" : latencyMs > target.latencyThresholdMs ? "DEGRADED" : "HEALTHY"; return { result: { id: crypto.randomUUID(), target, status: outcome, reason: errorMessage ?? reasonFor(outcome, statusCode, latencyMs, target), latencyMs, actualStatusCode: statusCode, checkedAt: new Date().toISOString() }, errorType }; }

export function scheduledBucket(endpointId: string, intervalMinutes: number, at: Date): { scheduledFor: string; deduplicationKey: string } { const intervalMs = intervalMinutes * 60_000, bucketMs = Math.floor(at.getTime() / intervalMs) * intervalMs; return { scheduledFor: new Date(bucketMs).toISOString(), deduplicationKey: `scheduled:${endpointId}:${bucketMs}` }; }
const messageFromJob = (job: JobRow): MonitoringQueueMessage => ({ version: 1, jobId: job.id, workspaceId: job.workspace_id, endpointId: job.endpoint_id, scheduledFor: job.scheduled_for, source: job.source });
async function publishMessages(queue: Queue<MonitoringQueueMessage>, messages: MonitoringQueueMessage[]): Promise<void> { for (let offset = 0; offset < messages.length; offset += QUEUE_BATCH_SIZE) await queue.sendBatch(messages.slice(offset, offset + QUEUE_BATCH_SIZE).map((body) => ({ body, contentType: "json" }))); }
const scheduleLimit = (raw: string | undefined) => { const value = Number(raw ?? DEFAULT_SCHEDULE_LIMIT); return Number.isInteger(value) && value > 0 ? Math.min(value, MAX_SCHEDULE_LIMIT) : DEFAULT_SCHEDULE_LIMIT; };
export async function scheduleChecks(env: Env, at = new Date()): Promise<{ due: number; recovered: number; published: number }> { const limit = scheduleLimit(env.MAX_JOBS_PER_SCHEDULE), now = at.toISOString(), stale = new Date(at.getTime() - STALE_QUEUED_MS).toISOString(); const recovered = (await env.DB.prepare("SELECT * FROM monitoring_jobs WHERE status='QUEUED' AND scheduled_for<=? ORDER BY scheduled_for LIMIT ?").bind(stale, limit).all<JobRow>()).results, remaining = Math.max(0, limit - recovered.length); const due = remaining ? (await env.DB.prepare(`SELECT e.* FROM endpoints e WHERE e.enabled=1 AND julianday(?) >= julianday(COALESCE((SELECT MAX(j.scheduled_for) FROM monitoring_jobs j WHERE j.endpoint_id=e.id AND j.source='SCHEDULED' AND j.status<>'FAILED'), e.created_at)) + (e.check_interval_minutes / 1440.0) ORDER BY e.updated_at LIMIT ?`).bind(now, remaining).all<EndpointRow>()).results : []; const created: JobRow[] = []; for (const endpoint of due) { const bucket = scheduledBucket(endpoint.id, endpoint.check_interval_minutes, at), id = crypto.randomUUID(); await env.DB.prepare("INSERT OR IGNORE INTO monitoring_jobs (id,workspace_id,endpoint_id,deduplication_key,source,status,scheduled_for,created_at,updated_at) VALUES (?,?,?,?,'SCHEDULED','QUEUED',?,?,?)").bind(id, endpoint.workspace_id, endpoint.id, bucket.deduplicationKey, bucket.scheduledFor, now, now).run(); const job = await env.DB.prepare("SELECT * FROM monitoring_jobs WHERE deduplication_key=? AND status='QUEUED'").bind(bucket.deduplicationKey).first<JobRow>(); if (job) created.push(job); } const unique = new Map([...recovered, ...created].map((job) => [job.id, job])); const messages = [...unique.values()].map(messageFromJob); await publishMessages(env.MONITORING_QUEUE, messages); const summary = { due: due.length, recovered: recovered.length, published: messages.length }; console.log("Monitoring schedule completed", { ...summary, scheduledAt: now }); return summary; }

const sanitizedError = (error: unknown) => (error instanceof Error ? error.message : "Infrastructure failure.").replace(/https?:\/\/\S+/gi, "[target]").replace(/\/api\/invitations\/[^/\s]+/gi, "/api/invitations/[redacted]").replace(/\/invite\/[^/\s]+/gi, "/invite/[redacted]").replace(/[A-Za-z0-9_-]{40,}/g, "[redacted]").slice(0, 500);
async function finishWithoutCheck(db: D1Database, jobId: string, reason: string, now: string) { await db.prepare("UPDATE monitoring_jobs SET status='FAILED',last_error=?,completed_at=?,updated_at=? WHERE id=? AND status<>'COMPLETED'").bind(reason, now, now, jobId).run(); }
export async function processQueueMessage(env: Env, raw: unknown, attempts: number): Promise<"ack" | "retry"> {
	const message = parseQueueMessage(raw); if (!message) { console.warn("Rejected invalid monitoring queue message", { outcome: "invalid_message" }); return "ack"; } const context = { jobId: message.jobId, endpointId: message.endpointId, source: message.source }; const job = await env.DB.prepare("SELECT * FROM monitoring_jobs WHERE id=? AND workspace_id=? AND endpoint_id=?").bind(message.jobId, message.workspaceId, message.endpointId).first<JobRow>(); if (!job) { console.warn("Monitoring job no longer exists", { ...context, outcome: "missing_job" }); return "ack"; } if (job.source !== message.source || job.scheduled_for !== message.scheduledFor) { await finishWithoutCheck(env.DB, job.id, "Queue message did not match its job.", new Date().toISOString()); return "ack"; } if (job.status === "COMPLETED" || job.status === "FAILED") return "ack";
	const endpoint = await env.DB.prepare("SELECT * FROM endpoints WHERE id=? AND workspace_id=?").bind(message.endpointId, message.workspaceId).first<EndpointRow>(); if (!endpoint) { await finishWithoutCheck(env.DB, job.id, "Endpoint was deleted before the check ran.", new Date().toISOString()); console.log("Monitoring job finalized", { ...context, outcome: "endpoint_deleted" }); return "ack"; } if (!endpoint.enabled) { await finishWithoutCheck(env.DB, job.id, "Endpoint is paused.", new Date().toISOString()); console.log("Monitoring job finalized", { ...context, outcome: "endpoint_paused" }); return "ack"; }
	const started = new Date().toISOString(), claim = await env.DB.prepare("UPDATE monitoring_jobs SET status='PROCESSING',attempt_count=attempt_count+1,started_at=COALESCE(started_at,?),last_error=NULL,updated_at=? WHERE id=? AND status='QUEUED'").bind(started, started, job.id).run(); if (!claim.meta.changes) { const current = await env.DB.prepare("SELECT status FROM monitoring_jobs WHERE id=?").bind(job.id).first<{ status: MonitoringJobStatus }>(); return current?.status === "COMPLETED" || current?.status === "FAILED" ? "ack" : "retry"; }
	try { const { result, errorType } = await executeCheck(targetFromRow(endpoint)), completed = new Date().toISOString(); await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO check_results (id,endpoint_id,job_id,checked_at,status_code,latency_ms,outcome,error_type,error_message) VALUES (?,?,?,?,?,?,?,?,?)").bind(result.id, endpoint.id, job.id, result.checkedAt, result.actualStatusCode, result.latencyMs, result.status, errorType, errorType ? result.reason : null), env.DB.prepare("UPDATE monitoring_jobs SET status='COMPLETED',completed_at=?,updated_at=?,last_error=NULL WHERE id=? AND EXISTS (SELECT 1 FROM check_results WHERE job_id=?)").bind(completed, completed, job.id, job.id)]); try { await evaluateIncident(env, result.id); } catch (incidentError) { console.error("Incident evaluation deferred", { ...context, resultId: result.id, outcome: "retry_on_cron", error: sanitizedError(incidentError) }); } console.log("Monitoring check completed", { ...context, outcome: result.status, statusCode: result.actualStatusCode, latencyMs: result.latencyMs }); return "ack"; } catch (error) { const detail = sanitizedError(error), now = new Date().toISOString(); if (attempts >= MAX_QUEUE_ATTEMPTS) { await finishWithoutCheck(env.DB, job.id, detail, now); console.error("Monitoring job exhausted retries", { ...context, outcome: "failed", error: detail }); return "ack"; } await env.DB.prepare("UPDATE monitoring_jobs SET status='QUEUED',last_error=?,updated_at=? WHERE id=? AND status='PROCESSING'").bind(detail, now, job.id).run(); console.warn("Monitoring infrastructure failure", { ...context, outcome: "retry", error: detail }); return "retry"; }
}

async function createManualJob(db: D1Database, queue: Queue<MonitoringQueueMessage>, id: string, workspaceId: string): Promise<Response> { const endpoint = await findEndpoint(db, id, workspaceId); if (!endpoint.enabled) throw new ApiError(409, "CONFLICT", "Paused endpoints cannot be checked."); const now = new Date().toISOString(), jobId = crypto.randomUUID(); await db.prepare("INSERT INTO monitoring_jobs (id,workspace_id,endpoint_id,deduplication_key,source,status,scheduled_for,created_at,updated_at) VALUES (?,?,?,?,'MANUAL','QUEUED',?,?,?)").bind(jobId, workspaceId, endpoint.id, `manual:${jobId}`, now, now, now).run(); try { await queue.send({ version: 1, jobId, workspaceId, endpointId: endpoint.id, scheduledFor: now, source: "MANUAL" }, { contentType: "json" }); } catch (error) { console.error("Manual monitoring job publication failed", { jobId, endpointId: endpoint.id, source: "MANUAL", outcome: "queued_for_recovery", error: sanitizedError(error) }); throw new ApiError(503, "SERVICE_UNAVAILABLE", "The check was saved but could not be queued yet. It will be retried automatically."); } return success({ jobId, status: "QUEUED" }, 202); }
async function getJob(db: D1Database, id: string, workspaceId: string): Promise<Response> { const job = await db.prepare("SELECT * FROM monitoring_jobs WHERE id=? AND workspace_id=?").bind(id, workspaceId).first<JobRow>(); if (!job) throw new ApiError(404, "NOT_FOUND", "Monitoring job not found."); const endpoint = await db.prepare("SELECT * FROM endpoints WHERE id=? AND workspace_id=?").bind(job.endpoint_id, workspaceId).first<EndpointRow>(), result = endpoint ? await db.prepare("SELECT r.* FROM check_results r JOIN endpoints e ON e.id=r.endpoint_id WHERE r.job_id=? AND e.workspace_id=? LIMIT 1").bind(job.id, workspaceId).first<ResultRow>() : null; const data: MonitoringJob = { id: job.id, endpointId: job.endpoint_id, source: job.source, status: job.status, scheduledFor: job.scheduled_for, attemptCount: job.attempt_count, lastError: job.last_error, createdAt: job.created_at, startedAt: job.started_at, completedAt: job.completed_at, result: result && endpoint ? resultFromRow(result, targetFromRow(endpoint)) : null }; return success(data); }
async function handleDemo(pathname: string): Promise<Response> { if (pathname.endsWith("/slow")) await new Promise((resolve) => setTimeout(resolve, 1200)); const status = pathname.endsWith("/failing") ? 500 : 200; return new Response(JSON.stringify({ status: status === 200 ? "ok" : "error", endpoint: pathname }), { status, headers: JSON_HEADERS }); }
async function incidentRoute(request: Request, env: Env, url: URL, workspace: WorkspaceAccess): Promise<Response | null> {
	if (url.pathname === "/api/incidents") {
		if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`);
		try { return success(await listIncidents(env.DB, workspace.id, url.searchParams)); }
		catch (error) { if (error instanceof Error && error.message.startsWith("VALIDATION:")) throw new ApiError(400, "VALIDATION_ERROR", error.message.slice(11)); throw error; }
	}
	const match = /^\/api\/incidents\/([^/]+)(?:\/(acknowledge|resolve|events|alerts))?$/.exec(url.pathname);
	if (!match?.[1]) return null;
	const id = decodeURIComponent(match[1]), action = match[2];
	if (!action && request.method === "GET") { const incident = await getIncident(env.DB, workspace.id, id); if (!incident) throw new ApiError(404, "NOT_FOUND", "Incident not found."); return success(incident); }
	if (action === "events" && request.method === "GET") { const events = await getIncidentEvents(env.DB, workspace.id, id); if (!events) throw new ApiError(404, "NOT_FOUND", "Incident not found."); return success(events); }
	if (action === "alerts" && request.method === "GET") { const alerts = await getIncidentAlerts(env.DB, workspace.id, id); if (!alerts) throw new ApiError(404, "NOT_FOUND", "Incident not found."); return success(alerts); }
	if (action === "acknowledge" && request.method === "POST") { const incident = await acknowledgeIncident(env.DB, workspace.id, id); if (!incident) throw new ApiError(404, "NOT_FOUND", "Incident not found."); if (incident === "CONFLICT") throw new ApiError(409, "CONFLICT", "Only an open incident can be acknowledged."); return success(incident); }
	if (action === "resolve" && request.method === "POST") { const incident = await resolveIncident(env, workspace.id, id); if (!incident) throw new ApiError(404, "NOT_FOUND", "Incident not found."); if (incident === "CONFLICT") throw new ApiError(409, "CONFLICT", "The incident is already resolved."); return success(incident); }
	throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`);
}
async function route(request: Request, env: Env): Promise<Response> {
	const url = new URL(request.url), path = url.pathname;
	if (["/api/demo/healthy", "/api/demo/slow", "/api/demo/failing"].includes(path)) { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return handleDemo(path); }
	if (path === "/api/auth/github") { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return beginGithub(request, env); }
	if (path === "/api/auth/github/callback") { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return githubCallback(request, env); }
	if (path === "/api/auth/session") { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return sessionResponse(request, env); }
	if (path === "/api/auth/logout") { if (request.method !== "POST") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return logout(request, env); }
	const auth = await authenticate(request, env.DB); validateOrigin(request, env);
	if (path === "/api/workspaces") { if (request.method === "GET") return listWorkspaces(auth); if (request.method === "POST") return createWorkspace(request, env, auth); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const invitationRecipientMatch = /^\/api\/invitations\/([^/]+)(?:\/(accept))?$/.exec(path); if (invitationRecipientMatch?.[1]) { const token = decodeURIComponent(invitationRecipientMatch[1]), action = invitationRecipientMatch[2]; if (!action && request.method === "GET") return getInvitation(env.DB, auth, token); if (action === "accept" && request.method === "POST") return acceptInvitation(env.DB, auth, token); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const memberItemMatch = /^\/api\/workspaces\/([^/]+)\/members\/([^/]+)$/.exec(path); if (memberItemMatch?.[1] && memberItemMatch[2]) { const workspace = workspaceById(auth, decodeURIComponent(memberItemMatch[1])), userId = decodeURIComponent(memberItemMatch[2]); if (request.method === "PATCH") return updateMember(request, env.DB, auth, workspace, userId); if (request.method === "DELETE") return removeMember(env.DB, auth, workspace, userId); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const memberMatch = /^\/api\/workspaces\/([^/]+)\/members$/.exec(path); if (memberMatch?.[1]) { const workspace = workspaceById(auth, decodeURIComponent(memberMatch[1])); if (request.method === "GET") return listMembers(env.DB, workspace); if (request.method === "POST") return setMember(request, env, auth, workspace); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const invitationAdminMatch = /^\/api\/workspaces\/([^/]+)\/invitations(?:\/([^/]+))?$/.exec(path); if (invitationAdminMatch?.[1]) { const workspace = workspaceById(auth, decodeURIComponent(invitationAdminMatch[1])), invitationId = invitationAdminMatch[2] ? decodeURIComponent(invitationAdminMatch[2]) : null; if (!invitationId && request.method === "GET") return listInvitations(env.DB, workspace); if (!invitationId && request.method === "POST") return createInvitation(request, env, auth, workspace); if (invitationId && request.method === "DELETE") return revokeInvitation(env.DB, auth, workspace, invitationId); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const workspace = workspaceFor(request, auth);
	if (path === "/api/endpoints") { if (request.method === "GET") return listEndpoints(env.DB, workspace.id); if (request.method === "POST") return createEndpoint(request, env.DB, workspace.id); throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); }
	const incidentResponse = await incidentRoute(request, env, url, workspace); if (incidentResponse) return incidentResponse;
	const jobMatch = /^\/api\/jobs\/([^/]+)$/.exec(path); if (jobMatch?.[1]) { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return getJob(env.DB, decodeURIComponent(jobMatch[1]), workspace.id); }
	const match = /^\/api\/endpoints\/([^/]+)(?:\/(check|results))?$/.exec(path); if (!match?.[1]) throw new ApiError(404, "NOT_FOUND", "Route not found."); const id = decodeURIComponent(match[1]), action = match[2];
	if (action === "check") { if (request.method !== "POST") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); return createManualJob(env.DB, env.MONITORING_QUEUE, id, workspace.id); }
	if (action === "results") { if (request.method !== "GET") throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`); const row = await findEndpoint(env.DB, id, workspace.id), limit = Number(url.searchParams.get("limit") ?? "50"); if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new ApiError(400, "VALIDATION_ERROR", "Query parameter 'limit' must be an integer from 1 to 100."); const { results } = await env.DB.prepare("SELECT r.* FROM check_results r JOIN endpoints e ON e.id=r.endpoint_id WHERE r.endpoint_id=? AND e.workspace_id=? ORDER BY r.checked_at DESC,r.id DESC LIMIT ?").bind(id, workspace.id, limit).all<ResultRow>(); return success(results.map((result) => resultFromRow(result, targetFromRow(row)))); }
	if (request.method === "GET") return success(await endpointFromRow(env.DB, await findEndpoint(env.DB, id, workspace.id))); if (request.method === "PATCH") return updateEndpoint(request, env.DB, id, workspace.id); if (request.method === "DELETE") { await findEndpoint(env.DB, id, workspace.id); await env.DB.prepare("DELETE FROM endpoints WHERE id=? AND workspace_id=?").bind(id, workspace.id).run(); return new Response(null, { status: 204 }); } throw new ApiError(405, "METHOD_NOT_ALLOWED", `Method ${request.method} not allowed.`);
}

export default {
	async fetch(request: Request, env: Env): Promise<Response> { const requestId = request.headers.get("cf-ray") ?? crypto.randomUUID(); try { return withSecurityHeaders(await route(request, env)); } catch (error) { const apiError = error instanceof ApiError ? error : new ApiError(500, "INTERNAL_ERROR", "An unexpected server error occurred."); (apiError.status >= 500 ? console.error : console.warn)("API request failed", { requestId, method: request.method, path: redactedRequestPath(request.url), status: apiError.status, code: apiError.code, error: sanitizedError(error) }); return withSecurityHeaders(failure(apiError, requestId)); } },
	async scheduled(controller: ScheduledController, env: Env): Promise<void> { const at = new Date(controller.scheduledTime); await cleanupAuth(env.DB, at); await expireInvitations(env.DB, at); await scheduleChecks(env, at); const evaluated = await recoverIncidentEvaluations(env); let alerts = 0; try { alerts = await recoverStaleAlerts(env, at); } catch (error) { console.error("Stale alert recovery deferred", { outcome: "retry_next_cron", error: sanitizedError(error) }); } console.log("Incident recovery completed", { evaluatedResults: evaluated, republishedAlerts: alerts }); },
	async queue(batch: MessageBatch<unknown>, env: Env): Promise<void> { const alertBatch = batch.queue === "endpoint-sentinel-alerts"; await Promise.all(batch.messages.map(async (message) => { try { const action = alertBatch ? await processAlertMessage(env, message.body, message.attempts) : await processQueueMessage(env, message.body, message.attempts); action === "ack" ? message.ack() : message.retry(); } catch (error) { console.error("Unhandled queue processing failure", { queue: batch.queue, outcome: "retry", error: sanitizedError(error) }); message.retry(); } })); },
} satisfies ExportedHandler<Env, unknown>;
