import { hashToken, type AuthContext, type WorkspaceAccess, type WorkspaceRole } from "./auth";
import { ApiError, isRecord, success } from "./http";

const DEFAULT_EXPIRY_DAYS = 7;
const MAX_EXPIRY_DAYS = 14;
const ACTIVE_INVITATION_LIMIT = 50;
type TeamEnv = Env & { APP_BASE_URL?: string };
type InvitationStatus = "PENDING" | "ACCEPTED" | "REVOKED" | "EXPIRED";
interface InvitationRow { id: string; workspace_id: string; workspace_name: string; invited_github_login: string; role: "MEMBER"; status: InvitationStatus; invited_by_user_id: string; inviter_login: string; inviter_name: string | null; accepted_by_user_id: string | null; expires_at: string; accepted_at: string | null; revoked_at: string | null; created_at: string; updated_at: string }

const randomToken = () => { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return btoa(String.fromCharCode(...bytes)).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, ""); };
const requireOwner = (workspace: WorkspaceAccess) => { if (workspace.role !== "OWNER") throw new ApiError(403, "FORBIDDEN", "Only workspace owners can manage the team."); };
export function normalizeGithubLogin(raw: string): string { const login = raw.trim().toLowerCase(); if (!/^(?!-)(?!.*--)[a-z0-9-]{1,39}(?<!-)$/.test(login)) throw new ApiError(400, "VALIDATION_ERROR", "Enter a valid GitHub username."); return login; }
const publicInvitation = (row: InvitationRow) => ({ id: row.id, invitedGithubLogin: row.invited_github_login, role: row.role, status: row.status, invitedBy: { githubLogin: row.inviter_login, displayName: row.inviter_name }, expiresAt: row.expires_at, acceptedAt: row.accepted_at, revokedAt: row.revoked_at, createdAt: row.created_at });
const invitationQuery = "SELECT i.*,w.name workspace_name,u.github_login inviter_login,u.display_name inviter_name FROM workspace_invitations i JOIN workspaces w ON w.id=i.workspace_id JOIN users u ON u.id=i.invited_by_user_id";

export async function expireInvitations(db: D1Database, at = new Date()): Promise<void> { const now = at.toISOString(); await db.prepare("UPDATE workspace_invitations SET status='EXPIRED',updated_at=? WHERE status='PENDING' AND expires_at<=?").bind(now, now).run(); }

export async function listInvitations(db: D1Database, workspace: WorkspaceAccess, at = new Date()): Promise<Response> { requireOwner(workspace); await expireInvitations(db, at); const rows = (await db.prepare(`${invitationQuery} WHERE i.workspace_id=? ORDER BY i.created_at DESC`).bind(workspace.id).all<InvitationRow>()).results; return success(rows.map(publicInvitation)); }

export async function createInvitation(request: Request, env: TeamEnv, auth: AuthContext, workspace: WorkspaceAccess, at = new Date()): Promise<Response> {
	requireOwner(workspace); let body: unknown; try { body = await request.json(); } catch { throw new ApiError(400, "VALIDATION_ERROR", "Request body must be valid JSON."); }
	if (!isRecord(body) || typeof body.githubLogin !== "string") throw new ApiError(400, "VALIDATION_ERROR", "A GitHub username is required."); const login = normalizeGithubLogin(body.githubLogin); if (login === auth.user.githubLogin.toLowerCase()) throw new ApiError(409, "CONFLICT", "You are already a member of this workspace."); if (body.role !== undefined && body.role !== "MEMBER") throw new ApiError(400, "VALIDATION_ERROR", "Invitations may grant only the MEMBER role.");
	const expiryDays = body.expiryDays === undefined ? DEFAULT_EXPIRY_DAYS : body.expiryDays; if (!Number.isInteger(expiryDays) || (expiryDays as number) < 1 || (expiryDays as number) > MAX_EXPIRY_DAYS) throw new ApiError(400, "VALIDATION_ERROR", `Expiry must be an integer from 1 to ${MAX_EXPIRY_DAYS} days.`);
	await expireInvitations(env.DB, at); const [membership, active] = await Promise.all([env.DB.prepare("SELECT 1 found FROM workspace_memberships m JOIN users u ON u.id=m.user_id WHERE m.workspace_id=? AND u.github_login=? COLLATE NOCASE").bind(workspace.id, login).first(), env.DB.prepare("SELECT COUNT(*) count FROM workspace_invitations WHERE workspace_id=? AND status='PENDING'").bind(workspace.id).first<{ count: number }>()]); if (membership) throw new ApiError(409, "CONFLICT", "That GitHub user is already a workspace member."); if ((active?.count ?? 0) >= ACTIVE_INVITATION_LIMIT) throw new ApiError(409, "CONFLICT", "This workspace has reached the active invitation limit.");
	const id = crypto.randomUUID(), token = randomToken(), now = at.toISOString(), expiresAt = new Date(at.getTime() + (expiryDays as number) * 86_400_000).toISOString();
	try { await env.DB.batch([env.DB.prepare("INSERT INTO workspace_invitations(id,workspace_id,invited_github_login,role,token_hash,status,invited_by_user_id,expires_at,created_at,updated_at) VALUES(?,?,?,'MEMBER',?,'PENDING',?,?,?,?)").bind(id, workspace.id, login, await hashToken(token), auth.user.id, expiresAt, now, now), env.DB.prepare("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,action,invitation_id,metadata,created_at) VALUES(?,?,?,'INVITATION_CREATED',?,?,?)").bind(crypto.randomUUID(), workspace.id, auth.user.id, id, JSON.stringify({ invitedGithubLogin: login, role: "MEMBER", expiresAt }), now)]); } catch (error) { if (error instanceof Error && /UNIQUE constraint failed/i.test(error.message)) throw new ApiError(409, "CONFLICT", "An active invitation already exists for that GitHub username."); if (error instanceof Error && /active invitation limit/i.test(error.message)) throw new ApiError(409, "CONFLICT", "This workspace has reached the active invitation limit."); throw error; }
	const base = env.APP_BASE_URL ? new URL(env.APP_BASE_URL).origin : new URL(request.url).origin, invitationUrl = `${base}/invite/${encodeURIComponent(token)}`; return success({ id, invitedGithubLogin: login, role: "MEMBER", status: "PENDING", expiresAt, createdAt: now, invitationUrl }, 201);
}

export async function revokeInvitation(db: D1Database, auth: AuthContext, workspace: WorkspaceAccess, invitationId: string, at = new Date()): Promise<Response> { requireOwner(workspace); await expireInvitations(db, at); const now = at.toISOString(), changed = await db.prepare("UPDATE workspace_invitations SET status='REVOKED',revoked_at=?,updated_at=? WHERE id=? AND workspace_id=? AND status='PENDING'").bind(now, now, invitationId, workspace.id).run(); if (!changed.meta.changes) { const exists = await db.prepare("SELECT status FROM workspace_invitations WHERE id=? AND workspace_id=?").bind(invitationId, workspace.id).first<{ status: InvitationStatus }>(); if (!exists) throw new ApiError(404, "NOT_FOUND", "Invitation not found."); throw new ApiError(409, "CONFLICT", "Only a pending invitation can be revoked."); } await db.prepare("INSERT OR IGNORE INTO workspace_audit_events(id,workspace_id,actor_user_id,action,invitation_id,metadata,created_at) VALUES(?,?,?,'INVITATION_REVOKED',?,'{}',?)").bind(crypto.randomUUID(), workspace.id, auth.user.id, invitationId, now).run(); return new Response(null, { status: 204 }); }

async function invitationByToken(db: D1Database, token: string): Promise<InvitationRow | null> { if (token.length < 32 || token.length > 128) return null; return db.prepare(`${invitationQuery} WHERE i.token_hash=?`).bind(await hashToken(token)).first<InvitationRow>(); }
export async function getInvitation(db: D1Database, auth: AuthContext, token: string, at = new Date()): Promise<Response> { let row = await invitationByToken(db, token); if (!row) throw new ApiError(404, "NOT_FOUND", "Invitation not found."); if (row.status === "PENDING" && row.expires_at <= at.toISOString()) { await expireInvitations(db, at); row = { ...row, status: "EXPIRED", updated_at: at.toISOString() }; } const matches = row.invited_github_login.toLowerCase() === auth.user.githubLogin.toLowerCase(); const common = { invitedGithubLogin: row.invited_github_login, status: row.status, expiresAt: row.expires_at, matchesCurrentUser: matches }; return success(matches ? { ...common, workspace: { id: row.workspace_id, name: row.workspace_name }, role: row.role, invitedBy: { githubLogin: row.inviter_login, displayName: row.inviter_name } } : common); }

export async function acceptInvitation(db: D1Database, auth: AuthContext, token: string, at = new Date()): Promise<Response> {
	const row = await invitationByToken(db, token); if (!row) throw new ApiError(404, "NOT_FOUND", "Invitation not found."); const login = auth.user.githubLogin.toLowerCase(); if (row.invited_github_login.toLowerCase() !== login) throw new ApiError(403, "FORBIDDEN", `This invitation is for @${row.invited_github_login}.`); const now = at.toISOString(); if (row.status === "PENDING" && row.expires_at <= now) { await expireInvitations(db, at); throw new ApiError(409, "CONFLICT", "This invitation has expired."); } if (row.status === "REVOKED") throw new ApiError(409, "CONFLICT", "This invitation was revoked."); if (row.status === "EXPIRED") throw new ApiError(409, "CONFLICT", "This invitation has expired."); if (row.status === "ACCEPTED" && row.accepted_by_user_id !== auth.user.id) throw new ApiError(409, "CONFLICT", "This invitation has already been used.");
	if (row.status === "PENDING") await db.batch([db.prepare("UPDATE workspace_invitations SET status='ACCEPTED',accepted_by_user_id=?,accepted_at=?,updated_at=? WHERE id=? AND status='PENDING' AND expires_at>?").bind(auth.user.id, now, now, row.id, now), db.prepare("INSERT OR IGNORE INTO workspace_memberships(workspace_id,user_id,role,created_at,updated_at) SELECT workspace_id,?,'MEMBER',?,? FROM workspace_invitations WHERE id=? AND status='ACCEPTED' AND accepted_by_user_id=?").bind(auth.user.id, now, now, row.id, auth.user.id), db.prepare("INSERT OR IGNORE INTO workspace_audit_events(id,workspace_id,actor_user_id,action,target_user_id,invitation_id,metadata,created_at) SELECT ?,workspace_id,?,'INVITATION_ACCEPTED',?,id,'{}',? FROM workspace_invitations WHERE id=? AND status='ACCEPTED' AND accepted_by_user_id=?").bind(crypto.randomUUID(), auth.user.id, auth.user.id, now, row.id, auth.user.id)]);
	const accepted = await db.prepare("SELECT status,accepted_by_user_id,workspace_id FROM workspace_invitations WHERE id=?").bind(row.id).first<{ status: InvitationStatus; accepted_by_user_id: string | null; workspace_id: string }>(); if (accepted?.status !== "ACCEPTED" || accepted.accepted_by_user_id !== auth.user.id) throw new ApiError(409, "CONFLICT", "This invitation is no longer available."); return success({ accepted: true, alreadyAccepted: row.status === "ACCEPTED", workspace: { id: row.workspace_id, name: row.workspace_name }, role: "MEMBER" });
}

async function memberRole(db: D1Database, workspaceId: string, userId: string): Promise<WorkspaceRole | null> { return (await db.prepare("SELECT role FROM workspace_memberships WHERE workspace_id=? AND user_id=?").bind(workspaceId, userId).first<{ role: WorkspaceRole }>())?.role ?? null; }
export async function updateMember(request: Request, db: D1Database, auth: AuthContext, workspace: WorkspaceAccess, userId: string, at = new Date()): Promise<Response> { requireOwner(workspace); let body: unknown; try { body = await request.json(); } catch { throw new ApiError(400, "VALIDATION_ERROR", "Request body must be valid JSON."); } if (!isRecord(body) || (body.role !== "OWNER" && body.role !== "MEMBER")) throw new ApiError(400, "VALIDATION_ERROR", "Role must be OWNER or MEMBER."); const current = await memberRole(db, workspace.id, userId); if (!current) throw new ApiError(404, "NOT_FOUND", "Workspace member not found."); const now = at.toISOString(), changed = await db.prepare("UPDATE workspace_memberships SET role=?,updated_at=? WHERE workspace_id=? AND user_id=? AND (role<>'OWNER' OR ?='OWNER' OR (SELECT COUNT(*) FROM workspace_memberships WHERE workspace_id=? AND role='OWNER')>1)").bind(body.role, now, workspace.id, userId, body.role, workspace.id).run(); if (!changed.meta.changes && current === "OWNER" && body.role === "MEMBER") throw new ApiError(409, "CONFLICT", "The final workspace owner cannot be demoted."); if (current !== body.role) await db.prepare("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,action,target_user_id,metadata,created_at) VALUES(?,?,?,'MEMBER_ROLE_CHANGED',?,?,?)").bind(crypto.randomUUID(), workspace.id, auth.user.id, userId, JSON.stringify({ fromRole: current, toRole: body.role }), now).run(); return success({ userId, role: body.role }); }
export async function removeMember(db: D1Database, auth: AuthContext, workspace: WorkspaceAccess, userId: string, at = new Date()): Promise<Response> { requireOwner(workspace); const current = await memberRole(db, workspace.id, userId); if (!current) throw new ApiError(404, "NOT_FOUND", "Workspace member not found."); const removed = await db.prepare("DELETE FROM workspace_memberships WHERE workspace_id=? AND user_id=? AND (role<>'OWNER' OR (SELECT COUNT(*) FROM workspace_memberships WHERE workspace_id=? AND role='OWNER')>1)").bind(workspace.id, userId, workspace.id).run(); if (!removed.meta.changes) throw new ApiError(409, "CONFLICT", "The final workspace owner cannot be removed."); const now = at.toISOString(); await db.prepare("INSERT INTO workspace_audit_events(id,workspace_id,actor_user_id,action,target_user_id,metadata,created_at) VALUES(?,?,?,'MEMBER_REMOVED',?,'{}',?)").bind(crypto.randomUUID(), workspace.id, auth.user.id, userId, now).run(); return new Response(null, { status: 204 }); }
