import { useEffect, useState } from "react";
import DashboardApp from "./DashboardApp";
import { ApiClientError, authApi, setActiveWorkspace, type AuthSession } from "./services/endpointsApi";

export default function App() {
	const oauthFailure = new URLSearchParams(window.location.search).get("authError");
	const [session, setSession] = useState<AuthSession | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(oauthFailure ? "GitHub sign-in was cancelled or could not be completed." : null);
	const [workspaceId, setWorkspaceId] = useState<string | null>(null), [workspaceName, setWorkspaceName] = useState(""), [creating, setCreating] = useState(false);
	async function loadSession() { setLoading(true); if (!oauthFailure) setError(null); try { const current = await authApi.session(); setSession(current); const first = current.workspaces[0]?.id ?? null; setWorkspaceId(first); setActiveWorkspace(first); } catch (cause) { if (!(cause instanceof ApiClientError && cause.status === 401)) setError(cause instanceof Error ? cause.message : "Authentication could not be checked."); setSession(null); setActiveWorkspace(null); } finally { setLoading(false); } }
	useEffect(() => { if (oauthFailure) window.history.replaceState({}, "", window.location.pathname); void loadSession(); const expired = () => { setSession(null); setWorkspaceId(null); setActiveWorkspace(null); setError("Your session expired. Sign in again to continue."); }; window.addEventListener("endpoint-sentinel:unauthorized", expired); return () => window.removeEventListener("endpoint-sentinel:unauthorized", expired); }, []);
	async function logout() { try { await authApi.logout(); } finally { setSession(null); setWorkspaceId(null); setActiveWorkspace(null); } }
	async function createWorkspace() { if (workspaceName.trim().length < 2) return; setCreating(true); setError(null); try { const workspace = await authApi.createWorkspace(workspaceName); setSession((current) => current ? { ...current, workspaces: [...current.workspaces, workspace] } : current); setWorkspaceId(workspace.id); setActiveWorkspace(workspace.id); setWorkspaceName(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Workspace could not be created."); } finally { setCreating(false); } }
	if (loading) return <main className="es-auth"><div className="es-auth-card"><h1>Endpoint Sentinel</h1><p role="status">Checking your secure session…</p></div></main>;
	if (!session) return <main className="es-auth"><div className="es-auth-card"><div className="es-auth-mark" aria-hidden="true">ES</div><h1>Endpoint Sentinel</h1><p>Secure, queue-driven endpoint monitoring for your team.</p>{error ? <p className="es-form__error" role="alert">{error}</p> : null}<a className="es-btn es-btn--primary es-auth-login" href="/api/auth/github?returnTo=/">Continue with GitHub</a><small>Authentication is handled by GitHub. Endpoint Sentinel never stores your GitHub access token.</small></div></main>;
	if (!workspaceId) return <main className="es-auth"><div className="es-auth-card"><h1>Create a workspace</h1><p>Signed in as <strong>@{session.user.githubLogin}</strong>. You do not have access to the existing workspace.</p><label className="es-form__field"><span className="es-form__label">Workspace name</span><input className="es-form__input" value={workspaceName} maxLength={80} onChange={(event) => setWorkspaceName(event.target.value)} /></label><button className="es-btn es-btn--primary" disabled={creating || workspaceName.trim().length < 2} onClick={() => void createWorkspace()}>{creating ? "Creating…" : "Create workspace"}</button><button className="es-btn" onClick={() => void logout()}>Sign out</button>{error ? <p className="es-form__error" role="alert">{error}</p> : null}</div></main>;
	return <><header className="es-account-bar"><div className="es-account-user">{session.user.avatarUrl ? <img src={session.user.avatarUrl} alt="" referrerPolicy="no-referrer" /> : <span aria-hidden="true">{session.user.githubLogin.slice(0, 1).toUpperCase()}</span>}<div><strong>{session.user.displayName ?? session.user.githubLogin}</strong><small>@{session.user.githubLogin}</small></div></div><div className="es-account-actions">{session.workspaces.length > 1 ? <label>Workspace<select value={workspaceId} onChange={(event) => { setWorkspaceId(event.target.value); setActiveWorkspace(event.target.value); }}><>{session.workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</></select></label> : <span>{session.workspaces[0]?.name}</span>}<button className="es-btn" type="button" onClick={() => void logout()}>Sign out</button></div></header><DashboardApp key={workspaceId} /></>;
}
